### ISSUE TITLE
Multi-stage transitions

### ISSUE THREAD

**Issue by techniq** [drcmda/react-spring#10]
Not sure how this would work with spring-based animations, but it would be useful to be able to have multi-stage transitions.  For example, to replicate [this](https://sghall.github.io/resonance/#/redux-examples/packed-by-age), you:
- animating the leaving items first
- update the existing items
- animate in the new items

Looking at the [source](https://github.com/sghall/resonance/blob/master/docs/src/routes/reduxExamples/packedByAge/components/Chart.js), react-move (previously known as resonance) does it with delays and passing arrays to enter/update/leave.  I don't know if react-spring could take in arrays as well and provide timings, or maybe explicitly specify the order of the lifecycle methods and waits for one to finish before starting the next:

```
<Transition
  enter={...}
  update={...}
  leave={...}
  order={'leave','update','enter'}
>
</Transition>
```
I don't know if this would be a good API (and work), but just another use case to think about.

**Comment by drcmda** [comment]
I guess it would come down to this:

1. plain userland using `onRest` where the animations reside in this.state, something like this: https://codesandbox.io/s/0qxxxljrvp
2. Making Transition more complex
3. Wrapping Transition into a class that reloads it using `onRest` 

I kind of like userland because it gives lots of finecontrol and it's actually quite easy to pull off. Otherwise the option to do this out of the box would be nice, too, if it's flexible enough.

**Comment by drcmda** [comment]
Another idea would be a generic Chaining primitive that would be able to define rules (onRest or delays) and simply forward stuff to the wrapping component, which could be a Spring, Transition, Trail, etc. I think i'd like that best.

**Comment by drcmda** [comment]
This probably isn't exactly related to the Transition component, but a little work on this and we have a generic component that can script just about anything. I am seeing it do chains, react to user interaction or switch primitives (go from trail to transition for instance).

![keyframes](https://user-images.githubusercontent.com/2223602/38492369-eccb79aa-3bee-11e8-8711-8786c7e9e652.gif)

https://codesandbox.io/s/j1w4355593

**Comment by techniq** [comment]
@drcmda that's looking great!

**Comment by techniq** [comment]
I like the imperative nature of `<Keyframe script={async () => {...} />`. I just now looked at React-Native's Animated and saw they have [parallel, sequence, stragger, and delay](https://facebook.github.io/react-native/docs/animated.html#composing-animations).  To sure if a similar preset could be offered here as well?

```jsx
<Sequence>
  <Spring ... />
  <Spring ... />
  <Spring ... />
</Sequence>
```

I like in your example you don't have to await one of your frictionless (but add an explicit delay).  Could also maybe have:

```jsx
<Sequence>
  <Spring ... />
  <Spring await={false} ... />
  <Delay value={2000} />
  <Spring ... />
</Sequence>
```

just bike-shedding right now 😄

**Comment by drcmda** [comment]
More primitives would be great anyways. That's the neat thing about animated, wrapping it [isn't expensive](https://github.com/drcmda/react-spring/blob/master/src/Keyframes.js).

PS. made a slightly more complex demo: https://codesandbox.io/embed/zl35mrkqmm

**Comment by joshperrin** [comment]
Hey there, I've been scouring the docs and examples trying to figure out how to do a Keyframes.Transition, but have yet to find a solution. I see in the Full API docs that the Keyframes has Transition functionality, but I can't seem to figure it out.

Maybe I'm not understanding the functionality completely, I was expecting to be able to use the keyframe to create a multi staged transition on enter and leave. I'm looking to have an element animate a transform, and then animate width when an item enters, and then reverse that when it exits.

Wondering if you could point me in the right direction, thanks!

**Comment by drcmda** [comment]
Keyframes are if you need to declare slots like open/closed/... or if you want to drive an animation by code. Your case seems to be a simple transition with from/enter/leave/update props. 

from = base state

enter = from -> appearing state

leave = current -> disappearing state

update = an update happened that was neither an exit or leave (other elements went in or out)

You can look into mauerwerk's source for some ideas: https://github.com/drcmda/mauerwerk/blob/master/src/index.js

**Comment by joshperrin** [comment]
Is it possible in the enter transition to have it have two stages? Kind of like the keyframe can accept a function, and then delay or wait between animations?

I'm looking for my enter animation on my Transition to animate the width property, wait for that to finish, then animate the transform property.

thanks!

**Comment by drcmda** [comment]
@joshperrin i think it could be possible with the update prop. I'm super busy right now to delve into this but in theory it should work. Probably the easiest would be to just give those two props different configs:

    enter={{ width: 100, transform: 'scale(1.5)', config: name => 
      name === 'width'
        ? ({ tension: 10, friction: 10 })
         : ({ tension: 10, friction: 50 })

When you use the ocillator spring (look for it on the GH front page), then you can also play around with the "mass" property.

**Comment by drcmda** [comment]
@techniq  @joshperrin took a while, but transition has a delay prop now that can trail adds/removes. See: http://react-spring.surge.sh/transition#props

It doesn't yet allow ordering and updates aren't trailed, but the foundation is there and it could easily be adjusted.
