### ISSUE TITLE
5.3.2 version break auto height animation

### ISSUE THREAD

**Issue by tanyaisinmybed** [drcmda/react-spring#101]
auto height example with lib version **5.3.2**:
[https://codesandbox.io/s/l4wro9ykz](https://codesandbox.io/s/l4wro9ykz)

auto height example with lib version **5.3.1**:
[https://codesandbox.io/s/q3726xryqq](https://codesandbox.io/s/q3726xryqq)

In 5.3.2 height animated from 0px to 1px

**Comment by drcmda** [comment]
@tanyaisinmybed should be fixed - fix-patch.js wasn't even loaded due to some minor refactoring recently.

**Comment by Pjata** [comment]
This seems to be still a problem.

**Comment by drcmda** [comment]
should hopefully be fixed now
