### ISSUE TITLE
How to animate width and display?

### ISSUE THREAD

**Issue by alvaro1728** [drcmda/react-spring#109]
I'd like to go from {width: 0, display: "none"} to {width: 300, display: "block"}.

```
<Spring from={{width: showing ? 0 : 300}} to={{width: showing ? 300 : 0}}>
  {style => <SomeComponent style={style} />}
</Spring>
```
If I just animate the width as shown above, the border and margins are still visible. I could animate them too, I suppose but... what's the best way to set display="block" at the beginning, when showing = true and back to "none" at the end, when showing = false?

Thanks,
Alvaro

**Comment by drcmda** [comment]
@alvaro1728 

There are several ways to do this, onRest for instance, but i would use regular props:

```jsx
<Spring from={{width: showing ? 0 : 300}} to={{width: showing ? 300 : 0}}>
  {style => <SomeComponent style={{ ...style, display: width === 0 ? 'none' : 'block' }} />}
</Spring>
```

If you use native spring:

```jsx
<Spring native from={{width: showing ? 0 : 300}} to={{width: showing ? 300 : 0}}>
  {style => <SomeComponent style={{ ...style, display: width === 0 ? 'none' : 'block' }} />}
</Spring>
```
