### ISSUE TITLE
TodoMVC demo bugs

### ISSUE THREAD

**Issue by chenglou** [drcmda/react-spring#11]
Repro:

- Go to https://codesandbox.io/embed/2pk8l7n7kn
- Type "asd" really quickly
- See that things unmount immediately without transition

Nice lib! =D

**Comment by drcmda** [comment]
Thanks for the all the inspiration and the impact that your work had on the React eco system at large!

Transition is such a hard piece of work, i saw how much effort was put into it in react-motion. I'll try my best fixing it.

**Comment by drcmda** [comment]
fixed in 4.0.2.
