### ISSUE TITLE
onRest() should only be called after a transition ends

### ISSUE THREAD

**Issue by bpierre** [drcmda/react-spring#110]
At the moment, `onRest` is called every time the component is rendered.

Here is a demo to compare this behavior with what react-motion does: https://codesandbox.io/s/3v99xomj2p

I think react-spring should follow the behavior of react-motion, where `onRest` only gets called after a transition ends.

**Comment by drcmda** [comment]
@bpierre that's curious, yes. Probably because it calls stop before rendering - which it shouldn't anyway since props didn't change. I'll look into this.

**Comment by drcmda** [comment]
@bpierre it should be fixed now ...

**Comment by bpierre** [comment]
It is! https://codesandbox.io/s/3v99xomj2p

Thank you 🙏
