### ISSUE TITLE
Can't get simple Mount/Unmount animation to work

### ISSUE THREAD

**Issue by melloc01** [drcmda/react-spring#113]
Hi guys, tried to chat on spectrum but I think issues on GH gets more attention.

Just wanted a fadeIn and fadeOut on my app to get started, what am I missing?

https://codesandbox.io/s/qk5qlxzkw9

**Comment by epilande** [comment]
@melloc01 
```diff
<Transition from={{ opacity: 0 }} enter={{ opacity: 1 }} leave={{ opacity: 0 }}>
-  {style => this.state.index % 2 === 0 && <animated.div style={{ ...style, background: '#12DBBF' }}>C</animated.div>}
+  {this.state.index % 2 === 0 && (style => <animated.div style={{ ...style, background: '#12DBBF' }}>C</animated.div>)}
</Transition>
```

**Comment by drcmda** [comment]
@melloc01 what @epilande said, just one addition, you're using animated.div but without giving transition the "native" flag.

**Comment by melloc01** [comment]
hm... Makes sense..

So, `<Transition />` watches for `falsy` / `not falsy` `children` to get the animations to play, think I'll take a look on the impl and try again on the app, thanks! :grimacing:

**Comment by drcmda** [comment]
It's a bit more tricky - the first implementation just wanted an array of functional children and keys to go along with that. Someone requested a shorter syntax to watch single entries, so if you only supply a single child, it'll take that as a key itself. To effectively it switches between fn and undefined (which renders nothing). But yeah, it works like that, internals can be weird sometimes.

**Comment by melloc01** [comment]
Cool! Thanks @drcmda -  from a newcomer: the shorthand for single entries is quite intuitive, actually I was writing it before reading the docs.
