### ISSUE TITLE
Component unmount is too slowly with transition & transform

### ISSUE THREAD

**Issue by jigsawye** [drcmda/react-spring#117]
Hi, I try to write a basic modal and use `Transition`. But the component unmount is too slowly.

Basic example: 
https://codesandbox.io/s/qqwvjx7394

When I click the open button everything is OK. But I can't click the open button immediately after click the close button, because the modal doesn't unmount in this moment.

Thank you for the awesome library 👍

**Comment by drcmda** [comment]
That can be helped, you can string values, too, not only numbers:

```jsx
leave={{ opacity: 0, transform: 'translateY(-100px)', pointerEvents: 'none' }}>
```

Now it leaves but won't receive events any longer.

Other than that you can control the speed via the config argument: https://github.com/drcmda/react-spring/blob/master/API.md#spring-configs

**Comment by jigsawye** [comment]
@drcmda Thanks for your solution, this problem is resolved!
But now I have another problem, I will open a new issue to describe it.
