### ISSUE TITLE
Issue using Transition with just native, from, enter, and leave

### ISSUE THREAD

**Issue by obetomuniz** [drcmda/react-spring#119]
I'm checking how the Transition works toggling 2 components using only native, from, enter, and leave properties (As the documentation says), but if I do quick toggles the components, an error message appears. Am I doing something wrong?

This is the bug:
![kapture 2018-06-17 at 1 39 24](https://user-images.githubusercontent.com/1680157/41504756-bc1ce624-71cf-11e8-9665-c25daafdaa37.gif)

This is my code:
https://codesandbox.io/s/km11q0xj47?view=editor

**Comment by drcmda** [comment]
I will take a look ...

**Comment by drcmda** [comment]
should work now in 5.3.16

**Comment by obetomuniz** [comment]
`react-spring@5.3.16` worked like a charm. Thanks for the prompt feedback/fix!
