### ISSUE TITLE
Timing demo uses deprecated "script" API

### ISSUE THREAD

**Issue by Adam13531** [drcmda/react-spring#125]
This code in the timing demo makes use of a `script` function for `Keyframes` even though [this page](https://github.com/drcmda/react-spring/blob/master/API.md#keyframes) says that it's deprecated.

https://github.com/drcmda/react-spring/blob/5eeedf37a020a617c5b36b93305ba0f4fdb9d489/examples/demos/timing/index.js#L38-L51

It would be nice if the example could be updated to use non-deprecated code.

**Comment by drcmda** [comment]
Will update after vacations 😎

**Comment by drcmda** [comment]
@Adam13531 done + a more refined api for raw scripting, and new section here explains it: https://github.com/drcmda/react-spring/blob/master/API-OVERVIEW.md#keyframes
