### ISSUE TITLE
Update Typescript definitions to support custom properties and to make 'key' property optional

### ISSUE THREAD

**Issue by szahn** [drcmda/react-spring#126]
```
<Transition native 
    from={{ opacity: 0}} 
    enter={{ opacity: 1}} 
    leave={{ opacity: 0}} 
    routeDetails={this.state.routeDetails}
    onInfoTableClose={this.onInfoTableClose}>
        {routeDetails && this.renderPropertyTable}
</Transition>
```

Typescript error:
Type '{ children: ({ onInfoTableClose, routeDetails, ...styles }: { [x: string]: any; onInfoTableClose:...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Transition<{}, { opacity: number; }>> & Readonly<{...'.\n  Type '{ children: ({ onInfoTableClose, routeDetails, ...styles }: { [x: string]: any; onInfoTableClose:...' is not assignable to type 'Readonly<TransitionProps<{}, { opacity: number; }>>'.\n    Types of property 'children' are incompatible.\n      Type '({ onInfoTableClose, routeDetails, ...styles }: { [x: string]: any; onInfoTableClose: any; routeD...' is not assignable to type '(params: { opacity: number; }) => string | number | boolean | {} | ReactElement<any> | ReactNodeA...'.\n        Types of parameters '__0' and 'params' are incompatible.\n          Type '{ opacity: number; }' is not assignable to type '{ [x: string]: any; onInfoTableClose: any; routeDetails: any; }'.\n            **Property 'onInfoTableClose' is missing in type '{ opacity: number; }'**."

**Comment by nelsliu9121** [comment]
1. What is the purpose for adding `routeDetails` and `onInfoTableClose` to `Transition` when the component make no use of that?
2. `key` property is considered important when rendering a list of components, what is the reason to make it optional? (See [this article](https://reactjs.org/docs/lists-and-keys.html#keys))

```jsx
<Transition
    native 
    from={{ opacity: 0}} 
    enter={{ opacity: 1}} 
    leave={{ opacity: 0}}
>
    {this.state.routeDetails && this.renderPropertyTable}
    // put this.onInfoTableClose inside this rendering func
</Transition>
```

**Comment by drcmda** [comment]
i'll close for now, types should be better now, merged a couple of prs. @nelsliu9121 is right btw, routeDetails onInfoTable and so on have no effect. You'd have to use render={...} instead of children, then it would forward. Otherwise you have access to scope anyway.
