### ISSUE TITLE
Max width scroll bar.

### ISSUE THREAD

**Issue by BlueBlazin** [drcmda/react-spring#131]
If you set `max-width` on `<Parallax>` and say, center it, the scrollbar no longer appears at the right end of the screen but rather the rather the right end of the parallax box.

How do you set the width property when using parallax if you don't want it to cover the full width of the viewport without this problem?

**Comment by drcmda** [comment]
@BlueBlazin could you make a codesandbox to demonstrate the problem?

**Comment by drcmda** [comment]
i'll close this for now to get on top of all the issues that crept up while i was away. i'll re-open if it's still pressing and a like i said a sandbox would be really nice to go on
