### ISSUE TITLE
`Trail` with `scale()` only working on the first child

### ISSUE THREAD

**Issue by VinSpee** [drcmda/react-spring#132]
Hi! This certainly feels like a bug.

simplified repro here: https://codesandbox.io/s/qlp6vr783j

i have an array of items in a `<Trail>` component. They're animated on both `opacity` and `transform`. The `transform` animation, however, is only taking effect on the _first_ item in the array. The rest of the items remain in the `from` state. This does [not occur](https://codesandbox.io/s/7z3z48209j) with the `<Transition>` component, which animates both properties as expected.

Am I doing something wrong here?

Thanks for the amazing library!

**Comment by drcmda** [comment]
@VinSpee indeed, looks like a bug. For some reason it ignores interpolations. I'm on vacation but meanwhile, do this:

```jsx
    <Trail
      keys={items.order}
      from={{ opacity: 0, scale: 0.75 }}
      to={{ opacity: 1, scale: 1 }}>
      {items.order.map(item => ({ scale, ...styles }) => (
          <div style={{ ...styles, transform: `scale(${scale})` }}>
            <div style={{ backgroundColor: 'cyan', padding: 10 }}>
              {items.data[item]}
            </div>
          </div>
        )
      )}
    </Trail>
```

Or, even better (as in, it's way more performant):

```jsx
import { Trail, animated } from 'react-spring'

    <Trail
      native
      keys={items.order}
      from={{ opacity: 0, scale: 0.75 }}
      to={{ opacity: 1, scale: 1 }}>
      {items.order.map(item => ({ scale, ...styles }) => (
        <animated.div style={{ ...styles, transform: scale.interpolate(s => `scale(${s})`) }}>
          <div style={{ backgroundColor: 'cyan', padding: 10 }}>
            {items.data[item]}
          </div>
        </animated.div>
      ))}
    </Trail>
```

**Comment by VinSpee** [comment]
awesome - thanks for the workaround! works swimmingly. now back to the beach!

**Comment by VinSpee** [comment]
I think I found another place this issue impacts: https://codesandbox.io/s/7z3z48209j

once again, only the first child is transitioned.

```jsx
<Trail
  native
  keys={currentWords.map(x => `${this.state.currentWords}-${x}`)}
  from={{ opacity: 0, y: '-100%' }}
  to={{ opacity: 1, y: '0%' }}
>
  {currentWords.map(item => ({ y, ...styles }) => (
    <animated.div
      style={{
        ...styles,
        transform: y.interpolate(s => `translateY(${s})`),
      }}
    >
      {item}{' '}
    </animated.div>
  ))}
</Trail>

**Comment by drcmda** [comment]
Anything that’s not a number is going to be interpolated, it’s most likely the same issue. I’ll get to it soon.

**Comment by drcmda** [comment]
I pushed .20 today which reduces the impact of it a little, it will at least run interpolations now. The problem generally is that interpolations are not adaptive, they can't "follow" other strings, which is somewhat of a limitation right now.

Workarounds: use raw numbers and interpolate yourself (all the above), or use a duration based trail: https://github.com/drcmda/react-spring/issues/97#issuecomment-392380139

**Comment by drcmda** [comment]
It's fixed now in .21

**Comment by VinSpee** [comment]
confirmed fixed in my case

https://codesandbox.io/s/6ym0r0oppk

thanks!

**Comment by drcmda** [comment]
@SnidelyWhiplash read this: https://github.com/drcmda/react-spring/blob/master/API-OVERVIEW.md#native-rendering-and-interpolation-demo

animated(View) and <Trail native from={...} to={...} ... /> will render natively, that means outside of React calling the function a bazillion times. It will render only once and the animation will be applied in a requestAnimationFrame-loop.

The rules otherwise are pretty much the same for react-spring web and RN. Only that RN's styles are a dit different, like transforms are an array, but they'll support native animations all the same as well as interpolations.

**Comment by SnidelyWhiplash** [comment]
Thanks @drcmda, I think I had my "aha" moment and everything's working great now. Cheers!
