### ISSUE TITLE
How can I access or keep current value of react spring?

### ISSUE THREAD

**Issue by dezman** [drcmda/react-spring#133]
I am animating elements multiple times in a loop, adjusting their height and margin bottom. At certain times I wish to keep the height wherever it happens to be and only continue animating the margin bottom.

```
let height = ...
let bottomSpace = ...

<Spring
  from={{
    height: 0,
    bottom: '100%',
    marginBottom: 0
  }}
  to={{
    height: height,
    bottom: '100%',
    marginBottom: bottomSpace
  }}
>
  {styles => <animated.div style={styles} className="mc-gee"></animated.div>}
</Spring>
```

If I don't pass in a height it breaks and if I pass undefined it starts animating to zero. Does react spring provide a way to access the previous value that it set internally, or just pass something to make it keep its value without animating anywhere else?

I made it work using a ref and `props.style.height._value` to get the current value, but it seems hacky, is there a better way?

**Comment by drcmda** [comment]
There’s the onFrame callback, but if you don’t want to animate certain props the best thing would be to not have them in the „to“ prop. If it crashes just for omitting a prop then that would be a bug, I’d be happy if you could isolate in a codesandbox.

**Comment by drcmda** [comment]
@dezman could you provide a codesandbox? i think this could be a misunderstanding. spring always remembers the last last state, "from" after the first animation is obsolete, from then on it just minds "to". Maybe you're trying to feed it from/to repeatedly. i'll close for now - will re-open if i get an example.
