### ISSUE TITLE
Transition children type does not allow conditional single child

### ISSUE THREAD

**Issue by felixeichhorst-jimdo** [drcmda/react-spring#135]
In the API overview it says we can use Transition components with a single child like this:
```jsx
<Transition from={{ opacity: 0 }} enter={{ opacity: 1 }} leave={{ opacity: 0 }}>
  {toggle && Component}
</Transition>
```

The children definition of `Transition` looks like that:
```javaScript
children: PropTypes.oneOfType([
  PropTypes.arrayOf(PropTypes.func),
  PropTypes.func,
]),
``` 
and the TypeScript type definition file like that:
```typeScript
children?: (
  params: DS & S,
) => ReactNode | Array<(params: DS & S) => ReactNode>;
```

Now I can neither use ternary notation nor logical AND without having TypeScript complaining about boolean or none not being assignable to the kind of expected function.

**Comment by drcmda** [comment]
I think someone fixed it already, but won’t be able to release for a week due to vacations (no laptop on me).
