### ISSUE TITLE
Is there any cross-browser support? Or information regarding Internet Explorer?

### ISSUE THREAD

**Issue by Monichre** [drcmda/react-spring#137]
If you have a question that doesn't concern bugs or requests, all i am asking you is to look for answers first before you hit submit. When you haven't found anything, please isolate your issue in a [codesandbox](https://codesandbox.io/), that makes it so much easier on our side to inspect and understand the issue. Also think about posting [in our community](https://spectrum.chat/react-spring) to keep the issue tracker focussed on bugs and features.

Thanks for understanding!

**Comment by drcmda** [comment]
Cross browser support is the end users concern, if you do not exclude node modules in your Babel config it will work in any IE version, provided you add some polyfills the lower you go. The lib itself is transformed with Babel-env, it does not ship a single polyfill (requestAnimationFrame, Promise, ...).

**Comment by drcmda** [comment]
closing this for now to get a better oversight of what needs to get fixed - if anything is unclear i can re-open
