### ISSUE TITLE
Have createAnimatedComponent automatically handle will-change

### ISSUE THREAD

**Issue by natew** [drcmda/react-spring#138]
Right now it seems you have to just set willChange yourself on style. But according to [this](https://dev.to/neshaz/everything-you-need-to-know-about-will-change-property-3f4k) it should only be set right before animating.

I want to test if this will fix some performance issues I'm having with Parallax. What I want to do is have it set `willChange: 'transform'` the frame before it begins animating on scroll, and then turn that back off once it stops.

But right now modifying Parallax.js would mean I'd have to call a re-render on every layer on screen to do that, presumably getting rid of a lot of the benefit rather than just mutating a single css prop on each layer.

*Solution*

If the component from createAnimatedComponent() had a mode to automatically detect what will change, and then delay changing it for a frame while it sets `will-change`, that would be a perfect solution.

**Comment by drcmda** [comment]
I have never heard of that, doesn’t willchange simply inform the browser to anticipate the element? 

I’ve fought a long time with browser performance and eventually gave up, the dom is slow and animating lots of things at the same time has a price. I don’t think these hacks really make that much of a difference in the end but who knows, profile it and then we know.

There was an article about parallax where one of the google guys went through all possible ways and hacks and eventually did it all in canvas. react-spring has a konva target (/dist/konva), it’s probably more effective to port parallax into react-konva.

**Comment by drcmda** [comment]
will re-open when its more clear if it makes a difference by profiling
