### ISSUE TITLE
Code Sandbox Examples are broken (or is it just me?)

### ISSUE THREAD

**Issue by guru-florida** [drcmda/react-spring#139]
All the code sandbox hosted examples show the Loading Sandbox then a black screen. Console shows this error:
```
common.0508cd62.chunk.js:1 TypeError: s is not a function
    at t.value (embed.cb4e825f.js:1)
    at Object.allowStateChanges (common.0508cd62.chunk.js:1)
    at common.0508cd62.chunk.js:1
    at Xt (common.0508cd62.chunk.js:1)
    at e.track (common.0508cd62.chunk.js:1)
    at c (common.0508cd62.chunk.js:1)
    at t.render (common.0508cd62.chunk.js:1)
    at h (common.0508cd62.chunk.js:1)
    at beginWork (common.0508cd62.chunk.js:1)
    at o (common.0508cd62.chunk.js:1)
```

Perhaps a few people can confirm if it's just me or not. I am running Chrome on Mac Version 67.0.3396.99 (Official Build) (64-bit). I tried a "Hard Reload" but no luck. Being a TypeError, could this be related to the new typescript work?

**Comment by guru-florida** [comment]
Iterestingly enough, I can copy the sandbox key (ex. vvmv6x01l5 for Trail example) and head over to code sandbox, click on any example there, then replace the key in the URL bar with vvmv6x01l5 and it loads and works. So maybe just an issue with code sanbox's embed, or maybe I am hitting a cached server with older but working code.

**Comment by drcmda** [comment]
They had a huge update today, maybe just a glitch. I’ll check back when vacations are over. :-)

**Comment by guru-florida** [comment]
It's working now, I just checked. :)
