### ISSUE TITLE
Looping Keyframes animation messes up when tab becomes inactive

### ISSUE THREAD

**Issue by DanielRakh** [drcmda/react-spring#143]
When creating a looping keyframes animation with an async function in a while loop and then making that tab inactive (by switching to a different tab for more than a few seconds) and coming back the animation messes up.

I'm guessing this mainly has to do with `delay` which i realize is **not** part of react-spring, but it was used in the examples and necessary for what i'm trying to pull off. 

What you're supposed to see and what you see if you never leave the tab:
[Magenta Rectangle][Tomato Rectangle][Magenta Rectangle][Tomato Rectangle]...etc

https://codesandbox.io/s/oooylrz1pz

Also, is this the right way to pull off this looping effect? Is there a better way?

**Comment by drcmda** [comment]
@DanielRakh the tab thing has to do with delay.

The looping thing, i think generally it's more a css puzzle than anything. I've made something that would work with colors at least, if you plan to use images for this, it would be a little more complex: https://codesandbox.io/s/jz0n0yz9y5

I've also made a small commit to make scripting easier, you can now pass a function into Keyframes:

    Keyframes.[primitive](async (next, props) => { ... })

Access to props is new as well, could come in handy.

**Comment by drcmda** [comment]
PS. i adapted the example a litte for my own purposes now. To get your effect simply delete the second call to `next` and put a `reset` into `Block`.
