### ISSUE TITLE
[question] Version of react for react-spring

### ISSUE THREAD

**Issue by PooLP** [drcmda/react-spring#145]
Hi,

What is the minimal version of React for react-spring ? 16 ?

Thanks

**Comment by drcmda** [comment]
Yes. Parallax also uses context, which could be polyfilled away, but most of the other primitives already use getDerivedStateFromProps which makes React 15 fall out.

**Comment by PascalSenn** [comment]
There is a polyfill for the new lifecycle methods as well: 
https://github.com/reactjs/react-lifecycles-compat

**Comment by drcmda** [comment]
Seeing this for the first time, neat! So it looks like a React 15 user could import a `Spring` and route this through the polyfill and that would be it?

**Comment by PooLP** [comment]
Thanks for response. You should add a badge in the readme file ![react_ 16](https://user-images.githubusercontent.com/582733/42615028-a0328eb8-85a8-11e8-9045-947d218e5540.png) (http://rmosolgo.github.io/react-badges/)

**Comment by drcmda** [comment]
@PooLP good idea, will do ...
