### ISSUE TITLE
Space between Parallax pages

### ISSUE THREAD

**Issue by schabluk** [drcmda/react-spring#147]
Hi,

Why there is a space between Parallax pages? Is this intentional?

Example showing white space between pages: https://codesandbox.io/s/mqy1mryqxp.

**Comment by drcmda** [comment]
That's the speed, you give it 0.2. That means these pages are deliberately out of place and the closer you move to their offset position the more they slide into their correct place. If you need a page that scroll in sync with the scrollbar use speed={0}. The shifting effect usually makes more sense for overlay elements (text, boxes, images, etc.).

**Comment by schabluk** [comment]
@drcmda thnaks! I was confusing this property with the 'speed' of the animation. Now it's clear for me, that the speed of the animation is controled via the config property of [Parallax component](https://github.com/drcmda/react-spring/blob/master/API.md#parallax).

**Comment by drcmda** [comment]
@schabluk the speed of the animation is controlled with the config prop, just like for all the other primitives. :-)

**Comment by jcafranca** [comment]
Thanks
