### ISSUE TITLE
[Werid Behavior] Trail will render wrong value except first child.

### ISSUE THREAD

**Issue by rockmandash** [drcmda/react-spring#148]
First, thank you for this wonderful library!
Please see this official example of Trail except opacity is 0 ~ 1
[![Edit x3w3mpj1qq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x3w3mpj1qq)
![image](https://user-images.githubusercontent.com/7580792/42613648-a2d0bbf0-85d4-11e8-8742-47d5a8b56f9f.png)
As you can see, when the animation ends, the number is decreasing rather than 1 (only the first child is 1)
I think this is unexpected behavior.
Don't know what do you think? Thanks.

**Comment by drcmda** [comment]
@rockmandash i think i know what it could be. Trail is pretty expensive so i throttle it a little, its probably missing the tail call. I'll look into it.

**Comment by rockmandash** [comment]
@drcmda Thank you for your fast reply.

**Comment by drcmda** [comment]
this took a while, had to figure out a way to do tail call throttling without adding too many bytes to this lib. but it should work as expected now.
