### ISSUE TITLE
Parallax support in Native

### ISSUE THREAD

**Issue by guru-florida** [drcmda/react-spring#149]
I noticed Parallax isnt supported in native yet. I've reviewed the Parallax.js in web and it seems like I might be able to change the AnimatedDiv to Animated.View. A lot of the other code seems transferrable to native. There are some styles for tranform/WebKitTransform/etc which may not be supported in Native css system. 

Any suggestions or concerns over porting this to Native folder? I can take a crack at it if it's not a big effort.

**Comment by drcmda** [comment]
@guru-florida would be nice, sure - go ahead, PR is very welcome. You can always reach me here if questions come up.

**Comment by guru-florida** [comment]
@drcmda So that I can prepare, do you see any impediments to porting it? Like for example, something that that is supported in React web but not in Native such as css styles, keyframing, etc. Do the Parallax and ParallaxLayer components rely pretty solely as a higher level component on top of the other react-spring functionality?

Thanks

**Comment by drcmda** [comment]
Sure, all primitives are just wrappers. I don't know react-native enough, but if there's something like onScroll/touchStart, then it would be a straight port.

**Comment by guru-florida** [comment]
Unfortunately, I can't seem to build react-spring *and* run that dist under native due to issues with babel7. Babel7 beta doesnt yet support react-native-preset but they are working on it. So I can't get my native app moved to babel7 for testing Parallax, and I get exception errors about babel6 and babel7 runtime loaded at the moment. There are threads ongoing about babel7 and react native so I will push this out for now.

I am closing this issue and do a PR when I am able to complete the work.

**Comment by drcmda** [comment]
You can copy the src folder, dump it into your project and import your { Parallax } from './src/targets/native'. That's how i tested RS against native as well. I simply created a project via create-react-native-app and placed it in there.
