### ISSUE TITLE
entry.interpolation._interpolation is not a function

### ISSUE THREAD

**Issue by PrecociouslyDigital** [drcmda/react-spring#152]
In [this pen](https://codesandbox.io/s/rm1lpv9wlm), if you add a score without changing the value of the score, the number in the top right ticks up normally. However, if the value of the score being added changes at all, then you get `Unhandled Rejection (TypeError): entry.interpolation._interpolation is not a function`. I am utterly baffled.

**Comment by drcmda** [comment]
```jsx
score: parseInt(event.target.value)
```

**Comment by PrecociouslyDigital** [comment]
Oh I see. Thank you!
