### ISSUE TITLE
How to chain keyframe animations?

### ISSUE THREAD

**Issue by A7DC** [drcmda/react-spring#156]
Hi,

Could someone explain to me the correct way to sequence animations? 

I have the following [Sandbox](https://codesandbox.io/s/pmy58qxxzx) where I want to animate the yellow background into the view (currently happening), but then animate the text differently (i.e delay the text animating into view by 300ms).

Thanks!

**Comment by drcmda** [comment]
There are several ways, 

1. you could try using multiple variables (y1, y2) and functional configs `config: name => name === 'y1' ? { tension: 50, friction: 40 } : config.gentle`

unfortunately `delay` isn't part or the config, so you can only increase the friction here.

2. two keyframes: https://codesandbox.io/embed/v6z61kx9wy

**Comment by A7DC** [comment]
Thanks for the response @drcmda, incredibly helpful! 🙏
