### ISSUE TITLE
Animate mount/unmount?

### ISSUE THREAD

**Issue by FezVrasta** [drcmda/react-spring#16]
I'd like to animate a single element that mounts/unmounts, what's the suggested way to handle this case?

I tried with `Transition` but it seems to like only 2 or more elements.

Thanks.

**Comment by FezVrasta** [comment]
Is it expected that with your example and these settings only the opacity gets animated?

```
          <Transition
            from={{ opacity: 0, rotation: '180deg', scale: 0.5 }}
            enter={{ opacity: 1, rotation: '0deg', scale: 1 }}
            leave={{ opacity: 0, rotation: '180deg', scale: 0.5 }}
          >
```

**Comment by drcmda** [comment]
@FezVrasta in 4.0.4 you can do:

    {condition && MyComponent}

All of them get animated, but rotation and scale are transform props, you can't spread them into styles just like that, you'd have to do something like this:

    {({ rotation, scale, ...rest }) => <div style={{ ...rest, transform: { rotation, scale } }} />}

**Comment by FezVrasta** [comment]
Thanks!

**Comment by drcmda** [comment]
@FezVrasta 

Wait, i'm silly, this is wrong. More like this:

```jsx
{({ rotation, scale, ...rest }) =>
    <div style={{ ...rest, transform: `rotation(${rotation}) scale(${scale})` } }} />}
```

😄

**Comment by jimthedev** [comment]
@drcmda Thanks for answering this. Would you be open to having this in the example to make it clear that these need to be handled differently? Currently it seems like the docs show them passed in but not being used. Had to find this issue to make sense of how they are handled. Cheers.

**Comment by jimthedev** [comment]
Updated my answer because even @drcmda's example didn't seem to work for me so I ended up going with interpolate to make scale work.

**Comment by drcmda** [comment]
@jimthedev interpolate is good when you need multiple values. Otherwise:

```jsx
transform: scale.interpolate(s => `scale(${s})`)
```

Or ...

```jsx
from={{ transform: 'scale(1)' }}
to={{ transform: 'scale(2)' }}>
  {styles => <animated.div styles={styles} ... />}
```

More on native rendering here: https://github.com/drcmda/react-spring/blob/master/API-OVERVIEW.md#native-rendering-and-interpolation-demo

**Comment by jimthedev** [comment]
Oh thank you that makes more sense.

**Comment by alexluong** [comment]
@drcmda Hi. I'm in the same situation with the OP (animate a single element that mounts/unmounts). I tried your solution as well as others (handle not condition as () => null). However, it gives me this error:

![screen shot 2018-07-11 at 11 19 49 pm](https://user-images.githubusercontent.com/26750127/42612442-f73381e2-8560-11e8-8fd4-428964c020c9.png)

This is my code:
![screen shot 2018-07-11 at 11 20 28 pm](https://user-images.githubusercontent.com/26750127/42612457-12d3a288-8561-11e8-8d45-51c3c59b7de3.png)

Is there something wrong with my code? Thanks!

**Comment by drcmda** [comment]
styles => MyComponent isn't React, you probably mean

```jsx
{message && MyComponent}
```

**Comment by rchrdnsh** [comment]
How would I go about doing this using the new hooks api @drcmda?

**Comment by slavagoreev** [comment]
> How would I go about doing this using the new hooks api @drcmda?

It works and allows to force reveal/hide the content of specific height.

```typescript
import React, { FunctionComponent } from 'react';
import { animated, useSpring } from 'react-spring';

import styles  from './Animations.scss';

export interface IRevealAnimationProps {
  height: number | string;
  initialOffset?: number | string;
  show?: boolean;
}

type SpringProps = { opacity: number; x: string | number; height:  string | number; }

export const RevealAnimation: FunctionComponent<IRevealAnimationProps> = ({
  height: elementHeight,
  initialOffset = 20,
  show = true,
  children
}) => {
  const { x, height, ...rest } = useSpring<SpringProps>({
    from: { opacity: 0, x: initialOffset, height: 0 },
    opacity: show ? 1 : 0,
    x: show ? 0 : initialOffset,
    height: show ? elementHeight : 0
  });
  return (
    <animated.div className={styles['reveal-animation']} style={{ ...rest, transform: x.interpolate(x => `translateY(${x}px)`) }}>
      <animated.div style={{ height }}>{children}</animated.div>
    </animated.div>
  );
};
```

```scss
.reveal-animation {
  will-change: transform, opacity;
  overflow: hidden;

  > div {
    display: block;
    overflow: hidden;
  }
}
```

**Comment by vai0** [comment]
> How would I go about doing this using the new hooks api @drcmda?

to answer this for anyone else ending up here, the [docs has an example](https://www.react-spring.io/docs/hooks/use-transition)
```javascript
const [show, set] = useState(false)
const transitions = useTransition(show, null, {
    from: { position: 'absolute', opacity: 0 },
    enter: { opacity: 1 },
    leave: { opacity: 0 },
})

return transitions.map(({ item, key, props }) =>
    item && <animated.div key={key} style={props}>✌️</animated.div>
)
```

**Comment by TomasSestak** [comment]
Is there please an example for v9? I cant get it working :/ i havent found it here https://aleclarson.github.io/react-spring/v9/breaking-changes/ and having item && doesnt seem to work when using boolean as items data

**Comment by JaredDahlke** [comment]
```
const myspring = useSpring({
        to: { opacity: 1 },
        from: { opacity: 0 },
        delay: 200	
    })

return (
		<animated.div style={myspring}>
		    <p> i will fade in on mount </p>
              </animated.div>
)
```
