### ISSUE TITLE
does this support react-native written in typescript?

### ISSUE THREAD

**Issue by fayte0618** [drcmda/react-spring#167]
I'm making a react-native app using typescript, and I noticed the typings are for the dom. Was searching the repo for react-native typings but could not find any?  Or I'm just missing some guide that may be you can help guide me to it? thanks

**Comment by lasseborly** [comment]
As far as I know there is no native TS typings available no.

**Comment by drcmda** [comment]
@fayte0618 could you make a PR? will gladly accept them!
