### ISSUE TITLE
Transition component for react-spring Native throws error on transform style property

### ISSUE THREAD

**Issue by eoghanmccarthy** [drcmda/react-spring#168]
I am trying to animate a small badge when it mounts and unmounts, however, the Transition component for react-spring Native throws errors any time I try to use the transform property.

For the example below the the error is 'You must specify exactly one property per transform object' which I am I think. All other attempts throw different errors. Is there something obvious I'm not doing? Is there an error with the Transition component?
 
```
const defaultStyles = {
  width: '90%',
  height: 50,
  backgroundColor: '#fd7a7a',
};

class Badge extends Component {
  render() {
    return (
      <Transition
        native
        from={{ opacity: 0, transform: [{ translateY: 0 }] }}
        enter={{ opacity: 1, transform: [{ translateY: 100 }] }}
        leave={{ opacity: 0, transform: [{ translateY: 0 }] }}
      >
        { (styles) => (
          <AnimatedView style={{ ...defaultStyles, ...styles }}>
            <Text>Welcome</Text>
          </AnimatedView>
        )}
      </Transition>
    );
  }
}
```

**Comment by drcmda** [comment]
@eoghanmccarthy This isn't how it works, the props to/from/enter/leave/update can either take name:value pairs or name:array(of values). You're looking for:

```jsx
  <Transition
    native
    from={{ opacity: 0, transformY: 0 }}
    enter={{ opacity: 1, transformY: 100 }}
    leave={{ opacity: 0, transformY: 0 }}>
    {({ ...styles, transformY }) => (
      <AnimatedView style={{ ...defaultStyles, ...styles, transform: [ { transformY }] }}>
        <Text>Welcome</Text>
      </AnimatedView>
    )}
  </Transition>
```

**Comment by eoghanmccarthy** [comment]
That's great, thank you!

**Comment by snobear** [comment]
I'm trying the above example, but getting:

```
'translateY' supplied to 'View' has been deprecated. Use the transform prop instead.
```

I tried moving it out of the `style` prop  and into a separate `transform` prop, e.g.:

```
  <AnimatedView style={{ ...defaultStyles, ...styles }} transform={[translateY]}>
...
```

but get the error

> Malformed calls from JS: field sizes are different

Tried a few different formats on that prop, but no deal. Any idea?

**Comment by drcmda** [comment]
It's deprecated? There's a transform in animated that normally takes care of style.transform, if transform is now a regular prop that would be a breaking change. Is there any sort of documentation for this so that i can support transform?

**Comment by snobear** [comment]
Is this the correct way to instantiate `AnimatedView` on react-native?

```
import { Transition, animated } from 'react-spring'
const AnimatedView = animated(View);
```

**Comment by drcmda** [comment]
Yes, that is correct. `View` comes straight from 'react-native' and animated extends it.
