### ISSUE TITLE
In React Native, the `delay` prop should not be passed onto `style`

### ISSUE THREAD

**Issue by SnidelyWhiplash** [drcmda/react-spring#169]
When you supply a `delay` prop, it seems like it's getting set on the `style` prop as well, and RN throws this error: `Invalid props.style key 'delay' supplied to 'View'`

```js
<Trail
  native
  config={config.wobbly}
  keys={myKeys}
  delay={this.state.myFlag ? 0 : 160}
  from={{
    opacity: 1,
    scale: 1,
  }}
  to={{
    opacity: this.state.myFlag ? 0 : 1,
    scale: this.state.myFlag ? 0.75 : 1,
  }}
>
  ...
</Trail>
```
I don't know if this is specific to the `<Trail>` component, or if it applies to all animations.

**Comment by drcmda** [comment]
Oops, looks like I forgot to filter it out. Will fix.

**Comment by drcmda** [comment]
@SnidelyWhiplash actually, it *should* already be fixed. Are you on the latest version? I've tried locally on the  ios emulator, an older version gets the warning, the current version filters it out.

**Comment by SnidelyWhiplash** [comment]
Thanks @drcmda, I was on `5.3.18`. Upgrading to `5.5.1` did fix it, however I'm now seeing this one: `Warning: Failed prop type: Invalid props.style key 'attach' supplied to 'View'.` which I don't _think_ I was getting before. Cheers for the help!

**Comment by drcmda** [comment]
Same issue, i need to filter it out. I don't notice it in the web because props aren't spread into styles like that. I'll release a new patch today.

**Comment by nguyenmanh1507** [comment]
I have a similar issue `Warning: Failed prop type: Invalid props.style key 'destroyed' supplied to 'View'.` Thanks for help

**Comment by drcmda** [comment]
Should be fixed now
