### ISSUE TITLE
Chaining animation with Transition?

### ISSUE THREAD

**Issue by monopixmonopix** [drcmda/react-spring#172]
My question is about the Transition/Keyframe.Transition

Is it possible something like this (chaining):
1) component mout > animation
2) component unmount > animation
3) component mount > animation start when above animation ends (2)

**Comment by drcmda** [comment]
Quite possibly yes, but could you describe the animation in more detail? I take it you want to animate more than one element, not just one and the same.

**Comment by monopixmonopix** [comment]
--- initial state
<Component data={['Lorem', 'ipsum']}>
   <span>Lorem</span>
   <span>ipsum</span>
</div>

---  When someone clicks the button, data changes
<Component data={['foo', 'bar']}>
   <span>foo</span>
   <span>bar</span>
</div>

1) Component mount with data 'Lorem ipsum', spans starts from>enter animation
2) Data was changed from 'Lorem ipsum' to 'foo bar'
  - 'lorem ipsum' animate enter>leave
  -  after 'lorem ipsum' leave, 'foo bar' apply from>enter animation ('foo bar' is waiting for the end 'lorem ipsum')


Thanks for the response

**Comment by monopixmonopix** [comment]
Thanks
