### ISSUE TITLE
This example (about interpolate from flubber) does not work with version 5.6.1 but still working with version 5.5.4

### ISSUE THREAD

**Issue by rainstormza** [drcmda/react-spring#175]
https://codesandbox.io/embed/lwpkp46om

I tried to use this example with my react project.
After I installed version 5.6.1 look like interpolate function does not work as expect, then I installed version 5.5.4 that example work fine again.

I think version 5.6.1 does not support interpolate function from flubber.
(not sure)

thanks

**Comment by drcmda** [comment]
Thanks, will look into it!

**Comment by drcmda** [comment]
@rainstormza quick solution, wrap the goNext into a requestAnimationFrame or remove the onRest and handle the interpolate in an onClick or something. I'll fix it this evening.

**Comment by drcmda** [comment]
should be fixed in the last version
