### ISSUE TITLE
Height auto weirdness

### ISSUE THREAD

**Issue by thebuilder** [drcmda/react-spring#176]
After updating to react-spring v5.6.x i'm seeing an issue with animating height between 0 and 'auto'.
If the height is changed while the `<Spring/ >` is active, it will stop updating the `height` untill it's resting again.

Sandbox demo: https://codesandbox.io/s/8z23zwvkm8
Try quickly toggling the open state, going: `open > close > open`. The text should animate into view, but it will instead pop up in after a second, once the spring is resting.

**Comment by drcmda** [comment]
The box looks good to me on 5.6.4.
