### ISSUE TITLE
Transition bug introduced in 5.4.3

### ISSUE THREAD

**Issue by berekuk** [drcmda/react-spring#182]
When one item is entering a <Transition> and another one is leaving simultaneously, there's some weird jumping around.

I bisected it and looks like https://github.com/drcmda/react-spring/commit/9f03dabb77eae8f9bf009cc740e2ae7f50d5afc1 broke something.

5.4.2 version (works correctly): https://codesandbox.io/s/xp70o87z2z

5.6.6 version (some jumping when moving from [2,3,4] to [1,2,3]; it looks the same on 5.4.3): https://codesandbox.io/s/l50zkqlx1q

**Comment by drcmda** [comment]
Should be fixed in the latest.

**Comment by drcmda** [comment]
PS. there's still a little jitter, but i think that's mainly css now, i've colored the transitions here: https://codesandbox.io/embed/3y00wx96n6 the way they're ordered should be good now.
