### ISSUE TITLE
Support ref forwarding on animated elements

### ISSUE THREAD

**Issue by psachs21** [drcmda/react-spring#184]
Currently, all animated div's cannot be associated to a ref. This makes any code that needs access to these nodes needlessly complicated.

**Comment by psachs21** [comment]
We can either go the route of styled components and the like (and name a special prop 'innerRef') to support older versions of react, or we can use the ref forwarding API.

**Comment by drcmda** [comment]
@psachs21 does this have any performance implications? Haven't actually tried forwardRef and read about it only in passing.

**Comment by drcmda** [comment]
@psachs21 i looked into it some more, animated.element is not a native browser element (div, span, etc) but a class. You can get the ref for it, which then points to it. To get a ref to the actual native element, you'd have to do:

```jsx
<animated.div
  ref={r => console.log(ReactDOM.findDOMNode(r))}
```

This is how the auto-fixers works, too: https://github.com/drcmda/react-spring/blob/master/src/targets/web/fix-auto.js#L30 it has to render out children once and receive a ref on it to measure it out.

The question now is, should this be automated? I looked into your PR and i still don't understand why we need forwaredRef. Is it not possible in React to read out the original ref and call it in the animated.el hoc?

**Comment by drcmda** [comment]
I merged it, will be in the next release, thanks a lot! 🙂
