### ISSUE TITLE
Leave Animation Not Working

### ISSUE THREAD

**Issue by Chrischuck** [drcmda/react-spring#186]
Hi there, 

I just recently started playing with react-spring and I copy and pasted some code from the examples and changed things around. Unfortunately, the leave animation isn't working. I have replicated the issue in code sandbox [here](https://codesandbox.io/s/zr6r63r2xl). The sandbox is almost exactly how I have things running in my project. My goal is to have the alert bar, which slides in from right to left, slide out from left to right when it is closed.

I did find this [issue](https://github.com/drcmda/react-spring/issues/43) but it looks like it was a bug in the code that you fixed. Maybe it's possibly related?

Best Regards,
Chris

**Comment by drcmda** [comment]
You're taking away the hole transition when you write:

```jsx
{alerts.length > 0 ? (
  <ul>
    <Transition
```

It wasn't obvious to me at first so i watched it screw up in disbelief - but it makes sense. Leave the condition to the transition component and it'll work. 😉

https://codesandbox.io/s/7jynom8816

**Comment by Chrischuck** [comment]
Thank you! I had that ternary there because I was getting an error for when the array was empty so I tried to do something like [this](https://github.com/drcmda/react-spring/issues/16). But in hindsight, it was probably my error since your fix works on your end and my end as well...
