### ISSUE TITLE
How do you get the height of an animated component using refs? 

### ISSUE THREAD

**Issue by A7DC** [drcmda/react-spring#188]
Does anyone have an example of where they've been able to use refs with animated elements? 

I need to get the height of an element when it is mounted, but because it's an animated component I'm not sure how?

Issue related to #184

**Comment by drcmda** [comment]
There's a PR pending for ref forwarding by @psachs21 just needs a little clarification on why a new prop has to be introduced. If you want to look into it or have some ideas that would be great. 

If you use animated.element, then that's a class you're getting back, not a div, so you can do this for now:

```jsx
ref={r => console.log(ReactDOM.findDOMNode(r))}
```

**Comment by drcmda** [comment]
PR's merged, you'll be able to use ref just like that in the upcoming release, just trying to get a couple of bugfixes in.
