### ISSUE TITLE
How to reverse item animation order through toggle value on "Trail" animation?

### ISSUE THREAD

**Issue by Jsalies** [drcmda/react-spring#196]
Hello, I would like to know if there is an option to reverse the animation order when we use "Trail". For a given list, The first child would be the first to move and when we change a toggle value, the first child would be the last one to move. Can I use Trail to do this or am I forced to use something else?

Thanks in advance

**Comment by Jsalies** [comment]
It works exactly has expected, thank you for your time and help!

**Comment by alexandernanberg** [comment]
@drcmda Trying to do this with `useTransition` but can't really figure it out. Is it still possible with hooks?

**Comment by cdlaporte** [comment]
Howdy all, I recently was trying to do this in a project of mine and ended up just using multiple springs with useSprings and dynamic delays. Basically something like this:
```javascript
    const [springs, setSprings] = useSprings(data.length, (i) => ({ z: 0 }))
    const hover = useGesture({
        onHover: state => {
            setSprings((i) => ({z: state.hovering ? 100 : 0, delay: state.hovering ? i*10 : (data.length*10) - (i*10)}));             
        }
    });
```
and then interpolating in the view. Hopefully this is useful for someone else--seemed to work well for my use case at least. 
Cheers!
