### ISSUE TITLE
Spring inside of Transition component is not removed until next addition/removal to the Transition

### ISSUE THREAD

**Issue by fernandofleury** [drcmda/react-spring#198]
Hey! I'm super excited to use react-spring. I was working with `react-transition-group` previously and decided to try and update my notifications system with it. Although I'm only facing a small issue:

Whenever a notification/item is removed, it will be flagged as destroyed but not removed from the DOM until another item enter or leave the Transition parent:

![image](https://user-images.githubusercontent.com/2780941/44490459-c8130500-a634-11e8-81a4-57db5148fddd.png)

And this is unfortunately causing a small issue where there is the removed item spacing still on the DOM:

![image](https://user-images.githubusercontent.com/2780941/44490534-eaa51e00-a634-11e8-835a-dde8dc02dd97.png)

Anything I could do here to force some sort of update on the Transition component or is it out of the scope of the library? I've read the docs but didn't find anything related to it.

Thanks!

**Comment by drcmda** [comment]
This is likely an error in react, can you update to at least 16.4.x and see if it persists?

**Comment by fernandofleury** [comment]
Hey @drcmda upgrading both react/react-dom to 16.4.x did the trick indeed! 😄 thank you for your help
