### ISSUE TITLE
Easing class - make it a namespace or a module

### ISSUE THREAD

**Issue by Andarist** [drcmda/react-spring#207]
This class has only static properties, all contained functions are useful on their own - I would propose to refactor this, they all should be just top level variables, reusable units. Or maybe even reuse what is already out there (i.e. `@popmotion/easing` - fully treeshakeable)

**Comment by drcmda** [comment]
you mean easing in addons? Sure, i think we could release a major when these are in together with the keyframe changes.

**Comment by Andarist** [comment]
That would be cool!

**Comment by drcmda** [comment]
I threw easings out, there are dozens on npm, starting with d3-ease, one worry less :-)
