### ISSUE TITLE
Globals

### ISSUE THREAD

**Issue by Andarist** [drcmda/react-spring#208]
Usage of those prevents tree-shaking. I'm not familiar with the codebase to say how exactly it should be refactored.

They main 2 approaches I would consider are:
- sibling files with different extensions - i.e. `.native.js`, `.universal.js` etc - that way you could import `/globals` file but have rollup "alias" it to the platform specific one during the build time, there would be no `inject*` calls
- introduce if logic based on build variable, i.e. `process.env.TARGET_PLATFORM`, same advantage - no `inject*` calls, imho this is less readable that former one because u support so many targets

The open question though is how to share web & konva code (they both target browser so if one wants to animate both he/she shouldnt have to pay double price) and have current Globals handled per platform, ideally without forcing a consumer to pay the globals double price if they only use 1 target.

**Comment by drcmda** [comment]
The first one is interesting. The only thing i think will fall out are runtime changes, for instance in @wilcoschoneveld 's PR: https://github.com/drcmda/react-spring/pull/178/files#diff-f0ec6bbc0966bef0299aef0370e305a6R11 It's a nice way to inject testable raf implementations and such. Globals per se shouldn't take that much space ... when you import the web target for instance, is there anything it *could* (or should) treeshake?

**Comment by Andarist** [comment]
> Globals per se shouldn't take that much space ... when you import the web target for instance, is there anything it could (or should) treeshake?

Globals that stay unused (because i.e. I've used a component using only part of them) could be tree-shaken.

Injecting for testing purposes is nice, but I think it's easy to workaround this - depending on how do you like write your tests.
