### ISSUE TITLE
Throttling bug with Transition

### ISSUE THREAD

**Issue by DmitryGG** [drcmda/react-spring#210]
When use Transition I have a bug: Transition childrens do not unmount sometimes.

You can see the bug here: https://youtu.be/osighmGWoUw

Repo: https://github.com/DmitryGG/animated-ui
CodeSandbox: https://codesandbox.io/s/github/DmitryGG/animated-ui

I can reproduce bug only when run CRA dev mode on my PC, and can't reproduce it in CodeSandbox.

I think it is because of low performance (for example record video or show DOM dev tool), as result animation throttling and bugging.

**Comment by drcmda** [comment]
Hard to track this one, in CSB it looks alright to me as well and currently all hang ups in transition should be fixed given that you're using react 16.4.x and not below. Could this maybe be the case?

**Comment by thelambdaparty** [comment]
I had a similar issue, and looks like it was introduced in 5.4.3 (https://codesandbox.io/s/nwlq0820mj - inspect element to see children not being unmounted), 5.4.2 works as expected. (or my code could be wrong?)

**Comment by drcmda** [comment]
Update to react and react-dom 16.4.x then it’ll work. React lifecycles were broken prior to that unfortunately.
