### ISSUE TITLE
5.6.7 breaks styled-components compatibility

### ISSUE THREAD

**Issue by aVileBroker** [drcmda/react-spring#213]
Perhaps there is a different/preferred way of styling animated components with styled-components that I'm not aware of, but react-spring `5.6.7` breaks components that are styled with styled-components.

[Example of working 5.6.6](https://codesandbox.io/s/o99vw473wy)
[Example of broken 5.6.7](https://codesandbox.io/s/4096wl9qyw)

The Example.js file is a simple example that tries to create a `styled(animated.div)`.

The error is:
```
Error
Cannot create styled-component for component: [object Object]
```

**Comment by drcmda** [comment]
I think this is styled-components, i updated the dependency in your box and it started working. I also have a working styled cox here: https://codesandbox.io/s/ovyvzv7lvz

**Comment by drcmda** [comment]
Strange that 2.x makes problems but who knows ... is it an option for you to just move up or shall we look into it?

**Comment by aVileBroker** [comment]
Hmm yeah I updated to 3.x and it seems to be working! Thanks for addressing this so quickly @drcmda!
