### ISSUE TITLE
Suggestion: Add more "motivation" in Readme.md of why using spring physics is a good idea vs. tweening. Also make it very clear no durations are used

### ISSUE THREAD

**Issue by johot** [drcmda/react-spring#214]
This is a suggestion from a first time user.

When I found out this library I thought it simply was a tweening library (and "spring" was just a cool/fitting name). I also immediately started looking for instructions on where to configure the duration of an animation :)

Now I totally understand why such a concept does not exist escpecially after looking at the react-motion authors react europe video.

**My suggestions would be to add this to Readme.md**
* Add a better "motivation" text. I know there are some under the "What is it?" section, but I think react-motion explains it better:

> For 95% of use-cases of animating components, we don't have to resort to using hard-coded easing curves and duration. Set up a stiffness and damping for your UI element, and let the magic of physics take care of the rest. This way, you don't have to worry about petty situations such as interrupted animation behavior. It also greatly simplifies the API.

* Make it very clear no durations are used since it's physics based.

Just some suggestions :D Thanks!

**Comment by drcmda** [comment]
Could you start a PR? I'm in the process of creating real docs currently and would take away most of the text on the GH front, it would be great to concentrate on the strengths then instead of going into coding technicalities like right now.

**Comment by johot** [comment]
Yes i'll see what I can do!

**Comment by drcmda** [comment]
Added a new section for it: http://react-spring.surge.sh/gotchas
