### ISSUE TITLE
Overflow doesn't change on enter

### ISSUE THREAD

**Issue by BernardoFBBraga** [drcmda/react-spring#216]
When changing overflow in from, enter and leave it doesn't change on enter.
To make this obvious, I've set up a demo of a panel that has an overflowing red box. So the red box should not show the overflow while opening and not show while closing but it should show when open.

https://codesandbox.io/s/j4871rm45w
In the code above, I'd like overflow to be hidden on from, visible on enter and hidden on leave.
However, it stays hidden on enter. If you look in the elements, you'll see that the style remains overflow: hidden
```
from={{ opacity: 0, height: 0, overflow: 'hidden' }}
enter={{ opacity: 1, height: 200, overflow: 'visible' }}
leave={{ opacity: 0, height: 0, overflow: 'hidden' }}>
```

Debugging, I see that if I don't set a value on 'from', it will take the value from 'enter', but doesn't take the value on 'leave'
https://codesandbox.io/s/9o6op231w4
```
from={{ opacity: 0, height: 0 }}
enter={{ opacity: 1, height: 200, overflow: 'visible' }}
leave={{ opacity: 0, height: 0, overflow: 'hidden' }}>
```

Another case, when I only set the value on leave, it takes the value on leave.
https://codesandbox.io/s/8kvn8vx5pj

```
from={{ opacity: 0, height: 0 }}
enter={{ opacity: 1, height: 200 }}
leave={{ opacity: 0, height: 0, overflow: 'hidden' }}
```

So I know Transition takes a overflow value on every stage, from, enter and leave. But when combining them, it doesn't work.

**Comment by drcmda** [comment]
@BernardoFBBraga it only took the "from" value and applied it, i changed it to "to" and hopefully it should be fixed. I ran your first example and it looked fine.

**Comment by BernardoFBBraga** [comment]
thanks @drcmda
