### ISSUE TITLE
Is there a way to see transform-origin: center when using the scale animation?

### ISSUE THREAD

**Issue by jetlej** [drcmda/react-spring#218]
I'd like the scale to occur from the center rather then from the left.

**Comment by drcmda** [comment]
You can set it, either on the object itself or in "from"

**Comment by jetlej** [comment]
Forgot to mention that I'm transform a canvas element, so normal CSS doesn't apply. Do you know of a way to do this?

**Comment by drcmda** [comment]
I have little knowledge about canvas unfortunately, i think you'll have a better chance on stackoverflow/reddit. This is pure css though im gonna close this for now.
