### ISSUE TITLE
browser export config

### ISSUE THREAD

**Issue by nrfm** [drcmda/react-spring#22]
Congrats on a great project!

I am not a rollup user and i am trying to setup the build to export a browser consumable file ( with React exclusions etc...) for lazy loading in a non webpack/rollup builder environment...

any pointers or docs on how to do this with react-spring?

**Comment by drcmda** [comment]
I can easily export react-spring as an umd, but i wonder what will happen with the dependencies, for instance https://github.com/react-community/normalize-css-color

React and PropTypes have umd builds, but this one - i think it doesn't.

**Comment by nrfm** [comment]
i tried using the `iife` version and the deps get left behind.

As a workaround I am gonna setup a minimal webpack project and require react-spring and export from there..

**Comment by drcmda** [comment]
```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8" />
  <title>Hello World</title>
  <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
  <script src="https://unpkg.com/prop-types@15.6/prop-types.min.js"></script>
  <script src="https://unpkg.com/react-spring@4.0.6/dist/react-spring.umd.js"></script>
  <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
</head>

<body>
  <div id="root"></div>
  <script type="text/babel">

      ReactDOM.render(
        <ReactSpring.Spring config={{ tension: 0, friction: 100 }} from={{ opacity: 0 }} to={{ opacity: 1 }}>
            {props => <h1 style={props}>Hello, world!</h1>}
        </ReactSpring.Spring>,
        document.getElementById('root')
      )

    </script>
</body>

</html>
```

4.0.6 now exports a UMD, it puts normalize-css-color into the bundle while it's at it.

**Comment by nrfm** [comment]
It works great!!
thanks!
