### ISSUE TITLE
Spring: onRest does not get triggered, if one animated value stays equal

### ISSUE THREAD

**Issue by AndreasFaust** [drcmda/react-spring#220]
I want to animate with Spring from { opacity: 1, transform: -50% } to { opacity: 1, transform: 0 }. This Spring is embedded in a larger, configurable script, where you need to have the apparently redundant { opacity: 1 }. But this property keeps onRest from being triggered. 
Is this a bug? And is there a way around that? For example, when I set the from-opacity to 0.99 (which is not a solution for me) it's working. 
Code sandbox: https://codesandbox.io/s/64kr4wm0o3

**Comment by drcmda** [comment]
this is a bug for sure 😓, thanks for the sandbox! For now i would recommend from: 0.99 even if it's a hack. i'll fix this in the meantime.

**Comment by AndreasFaust** [comment]
Thank you!

**Comment by drcmda** [comment]
@AndreasFaust should be fixed.

**Comment by AndreasFaust** [comment]
@drcmda Amazing. Thank you once again!
