### ISSUE TITLE
using with Transition & Trails & Keyframes & react router

### ISSUE THREAD

**Issue by irfanabliz** [drcmda/react-spring#221]
First of all thanks for this awesome library, it is very cool and straight forward to understand and get started with, I think the question i'm posting maybe really easy but I got stuck trying to figure out how to make it work. 

Basically I want to make a react routing animation where items slide in and out, I looked through the example for Transition with react routing, but encountered following problem, how would i control the items in this situations? Like make react routing and Transition and Trails fluid, so when user click on about it will slide out items one by one, and then switch to about page etc.. I hope this clarifies my problem. https://codesandbox.io/s/147qqvylvj here is what I have so far.

**Comment by drcmda** [comment]
Have you seen this? https://codesandbox.io/embed/zl35mrkqmm The principle should remain the same even for routes.

**Comment by irfanabliz** [comment]
heyy really appreciate you took the time to reply, I did try and follow the example above and so far I even used states to manage to do this https://codesandbox.io/s/147qqvylvj probably im still missing something ..

**Comment by drcmda** [comment]
Transition now can trail, see: http://react-spring.surge.sh/transition (the prop is called "delay" for now). That makes it easier - you can now simply remove your items and they'll trail out. In the upcoming major there will be a couple of additional options for trailing.
