### ISSUE TITLE
Possible event handler / cpu leak in react-spring

### ISSUE THREAD

**Issue by mreishus** [drcmda/react-spring#222]
I've recreated it in this sandbox.  https://codesandbox.io/s/ojj7l84q5y 

It has instructions for testing in the HTML View.  Maybe I'm using the Transition incorrectly, but I think there might be a CPU leak.

**Comment by mreishus** [comment]
In my testing, it does not happen in `5.6.11` but happens in `5.6.12` and later.

**Comment by drcmda** [comment]
@mreishus thanks for reporting, looks evil in there, it appends "NaN" over and over ... i'll look into it.

**Comment by drcmda** [comment]
Should be fine now!

**Comment by mreishus** [comment]
Looks to work great, thanks
