### ISSUE TITLE
Transition: on animation finished callbacks

### ISSUE THREAD

**Issue by alexfedoseev** [drcmda/react-spring#224]
There is a few similar cases that I can't handle w/ current `Transition` API.
1. A modal component renders form w/ some data. After modal is fully shown, i.e. mount animation is finished, I want to highlight some field (flash it once) but I'm not sure when/how to trigger this callback (using `setTimeout` is meh).
2. Same modal. After modal is closed I want to wipe out data from outer state. But if I do this on hide then user sees flash during an unmount animation. In `react-transition-group` there is a callback `onExited` that triggers function after unmount animation is finished (then I can safely wipe out data since modal is not visible at this point).

AFAICT `react-spring` doesn't provide such callbacks at the moment?

**Comment by drcmda** [comment]
There's onStart, onRest, onFrame. onRest would fire on still-stand. Of course "still stand" is a bit arbitrary in a transition because new stuff can come in any moment, so while it could work now for your case maybe it isn't a good idea there, you could try though.

**Comment by drcmda** [comment]
released it, all props are explained here: http://steady-impulse.surge.sh/transition

docz is buggy as hell unfortunately or else i'd have published the docs already, but some things only work in dev and fail in production, ...

**Comment by drcmda** [comment]
You can test it and see if it’s good enough, your input is definitively welcome.

**Comment by ruslanchek** [comment]
I have tested. There is only such methods as: 
`
onStart: () => {},
onRest: () => { },
onFrame: () => {},
`
And they don't depend on animation direction, so you can't do something after exit directly. But you can write some code to emulate that events using your transition state valiable let's say `isShowing`: 
```
onStart: () => {
   if(isShowing) {
    enterActive();
  } else {
    exitActive();
  }
}

onRest: () => {
  if(isShowing) {
    enterDone();
  } else {
    exitDone();
  }
}
```
