### ISSUE TITLE
Memory Leaks when using with react-router v4

### ISSUE THREAD

**Issue by theiliad** [drcmda/react-spring#227]
![image](https://user-images.githubusercontent.com/14989804/45530190-7551e680-b7b7-11e8-9da0-09340db83c62.png)

I'm receiving that error from my Home component when switching into a different route that de-renders it. **(Using `<Trail />` in Home)**

Seems like some listeners are not being removed. Is this a known bug?

**Comment by loopmode** [comment]
Still, the components should guard against this.
```
    componentDidMount() {
        this._isMounted = true;
    }
    componentWillUnmount() {
        this._isMounted = false;
        // kill any pending calculations
    } 
```
And instead of just using `this.setState(...)`, always use `this._isMounted && this.setState(...)` instead.

**Comment by drcmda** [comment]
I do this mostly everywhere where it matters. That's why i'd like to see a piece of code that produces it, somewhere i must've forgotten to put up mount checks.

**Comment by loopmode** [comment]
I get it from `Keyframes`. Just updated to latest version (`5.8.0`) and it's reproducible in my app.

I have `const AnimationContainer = Keyframes.Spring({ ... })` for an intro animation, and when you hit the browser back button before the animation is finished, it happens.

```
index.js:2178 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Keyframes (created by Component)
    in Component (created by Nodes)
    in Nodes
    in g
    in svg
    ...
```

However what's strange is... You seem to have a mount guard already: https://github.com/drcmda/react-spring/blob/master/src/Keyframes.js#L33
It's the only place calling setState in that file..

**Comment by loopmode** [comment]
Nevermind. Didn't do the update right - still had 5.6.10 in my DLL. Purged it and 5.8.0 is just fine.
