### ISSUE TITLE
Transition creating too many child when clicking fast

### ISSUE THREAD

**Issue by jmcbee** [drcmda/react-spring#229]
I have made a demonstration on the problem

https://codesandbox.io/s/m5nrr1pyr8

I'm looking at the react-router example here (https://codesandbox.io/embed/xo0lrqw2nz), and it doesn't seem to have the problem. I think it has got something do with the `keys` prop? I don't understand why it's value is `location.pathname`. I would really appreciate your help.

**Comment by vitalybe** [comment]
I am experiencing the same issue...

https://codesandbox.io/s/42rx0lq2z0

I would expect the transitioned item to appear/disappear with a wobble as I click quickly. Instead, Transition creates more nested items as I click.

How do I make it reuse the same item and continue the animation from where it stopped?
