### ISSUE TITLE
Feature request - Allow optionally setting duration based easings

### ISSUE THREAD

**Issue by jimmy-guo** [drcmda/react-spring#23]
Per our spectrum conversation:

I’m attempting to create a continuous sine wave animation. I’ve gotten pretty close with https://codesandbox.io/s/lx5nvqz6pq but noticed that the animation pauses between keyframes, likely due to friction deceleration. Would it make sense to optionally allow users to specify a duration-based easing for these kinds of zero-delay, linear, continuous animations?

(FYI - my initial approach was a Trail based animation similar to https://codesandbox.io/s/q9lozyymr9 but I needed the first element to continue along the sine wave before the last element finished animating, and even then each element’s animation would be affected by the preceding element so the amplitude of the sine wave would decrease the further they were from the first element.)

Thanks again for this delightful library!

**Comment by drcmda** [comment]
@jimmy-guo 

Added it ...

![easing](https://user-images.githubusercontent.com/2223602/38698233-b18255b4-3e94-11e8-9b65-3473bd24c065.gif)

I just need to think about how to add this without adding lots of weight to the lib. Maybe as an add-on package. But the way it works now is pretty cool anyway because now it could receive any implementation, from easings, to rk4 springs, to ios oscilator spring, etc.

**Comment by drcmda** [comment]
PS. right now this is how it looks

```jsx
import { Spring, Keyframes, animated, TimingAnimation, Easing } from 'react-spring'

<Keyframes
    reset
    native
    keys={items}
    impl={TimingAnimation}
    config={{ duration: 2000, easing: Easing.linear }}
    script={async next => {
        while (true) {
            await next(Spring, {
                from: { radians: 0, color: '#247BA0' },
                to: { radians: 2 * Math.PI },
            })
        }
    }}>
    {Content}
</Keyframes>
```

**Comment by drcmda** [comment]
@jimmy-guo 

it's merged:

https://codesandbox.io/s/q9lozyymr9

https://github.com/drcmda/react-spring/tree/master/src/addons

For kicks i also added IOS harmonic oscillator spring (which has an additional mass attribute), implementations are fully exchangeable now.
