### ISSUE TITLE
AnimatedValue listener gets called twice with last value (overshootClamping: true)

### ISSUE THREAD

**Issue by stnwk** [drcmda/react-spring#233]
Hi.

I am using react-spring `5.7.2` and I noticed that when imperatively animating a value and using `overshootClamping: true` the listener gets called twice with the last value, when it really should only get called once I suppose.

See https://codesandbox.io/s/mojy35jp68 for a reproduction (see console.logs)

**Comment by drcmda** [comment]
Will be fixed next release. Already made the fix but i have some other stuff in there that needs some testing

**Comment by stnwk** [comment]
Ok, thanks! :)

**Comment by drcmda** [comment]
should be fixed now
