### ISSUE TITLE
Keyframes doesn't use config with TimingAnimation and Konva

### ISSUE THREAD

**Issue by JulienUsson** [drcmda/react-spring#234]
Hello,

I want to have an animated dashed line with Konva and React-Spring but the config is not used.
Here is an example of my problem : https://codesandbox.io/s/3y9p9pr83p
The first part of the animation should be slower and linear but it isn't.
Thanks,

Julien Usson

**Comment by drcmda** [comment]
Very, very strange indeed. It's like as if it doesn't even know duration. But for some reason here it works: https://codesandbox.io/s/x7xrp39zp

I'll look into it

**Comment by drcmda** [comment]
should be fixed now
