### ISSUE TITLE
Sample project will not build?

### ISSUE THREAD

**Issue by roberthchapman** [drcmda/react-spring#235]
Hi, this library looks extremely useful but when you download the project to try the sample code, npm install produces many errors, what is the secret to getting it to build?

Thanks,
Rob

**Comment by drcmda** [comment]
you mean the examples, this link? https://github.com/drcmda/react-spring/tree/master/examples

Do you want it to run inside your own projects? Then you simply `npm install react-spring` and import it. I tried to run the instructions in the examples folder and it looks like the documentation engine (docz) is crashing the build right now. You can ignore it and move on:

    git clone --depth=1 https://github.com/drcmda/react-spring
    cd react-spring
    npm install (crashes ........ )
    cd examples
    npm install
    npm start

**Comment by roberthchapman** [comment]
Thanks, couldn't tell what to do when it wouldn't build, it runs fine now.  Many thanks, this is an excellent library that has been really well designed to maximise what effects you can produce while still maintaining some simplicity!
