### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by loopmode** [drcmda/react-spring#236]
I would appreciate a documentation of changes, probably just a typical `CHANGELOG.md` file.

Currently, it's hard / risky to just upgrade to the latest version, for example when digging out a previously stale project that depends on `react-spring`. It should be possible to get an overview of what has happened since the version one is currently using.

**Comment by drcmda** [comment]
I had one but found it troublesome to maintain. I think i'm trying github tag releases, like so: https://github.com/drcmda/react-spring/releases/tag/v5.8.0

**Comment by loopmode** [comment]
Ah, great, didn't check there. Thanks.

**Comment by drcmda** [comment]
I just made that ;-) But i'll try to keep it that way from now on ...
