### ISSUE TITLE
Getting Maximum update depth exceeded.

### ISSUE THREAD

**Issue by ciaoben** [drcmda/react-spring#237]
First, thanks for your work!

I am trying to test it in a project and I have simple snippet like this:

```
<Transition from={{ opacity: 0 }} enter={{ opacity: 1 }} leave={{ opacity: 0 }}>
          {this.state.showAdvancedFilters
            ? styles => (
                <form className={s.advancedSearch} style={styles}>
                  ciao
                </form>
              )
            : () => null}
        </Transition>
```

but as soon as `this.state.showAdvancedFilters` become true I get this error:
```
Maximum update depth exceeded.
```

Reading the docs I can't figure out what it is wrong.

**Comment by drcmda** [comment]
Could you make a small codesandbox? It's most likely not a problem with transition, what you want should be very simple to get: https://codesandbox.io/s/0q90lr47lp

**Comment by ciaoben** [comment]
@drcmda, unfortunately, I can't create a sandbox with the code of the codebase I am working on.

But reading about issue 238 I tried to update from react `16.3` to the last version and now it seems to work. It was like react does not show the points in the transition because the library worked well since I could see the log of the `styles` object updating.

**Comment by ciaoben** [comment]
I have updated the codesandox as I have a question if you can help.

https://codesandbox.io/s/616vq726lr

How can I animate the movement of the black div (to move with the animated component)? Because now it jumps between the different positions instead of following the sibling movement?

**Comment by drcmda** [comment]
There's a problem in the older react regarding getDerivedStateFromProps, it already caused lots of issues here unfortunately. But nothing we can do, just hope it eventually fades away as people upgrade. If something new comes up i'll be here.
