### ISSUE TITLE
Maximum update depth exceeded on height auto

### ISSUE THREAD

**Issue by ZikDead** [drcmda/react-spring#238]
Receiving error ` Maximum update depth exceeded.`, when heigth = 'auto'. Tried so many things...
As base, I used this examples:
https://codesandbox.io/embed/j150ykxrv
https://codesandbox.io/embed/pmjomxn60
```
import { Transition, animated } from 'react-spring';

class Component extends React.Component { //Same for PureComponent
        return (
            <Transition
                from={{ opacity: 0, height: 0 }}
                enter={{ opacity: 1, height: 'auto' }}
                leave={{ opacity: 0, height: 0 }}>
                {styles => <animated.div style={styles}>something</animated.div>}
            </Transition>
        );
    }
}
```

**Comment by drcmda** [comment]
These examples both seem to run with height auto, could you make one for your crashing code?

**Comment by ZikDead** [comment]
OMG. I found issue, I was trouble in react, react-dom 16.4.1.... I updated it to latest and all works well.

**Comment by drcmda** [comment]
Thanks for the update!
