### ISSUE TITLE
Spring interpolation throws an exception when the `to` value is null

### ISSUE THREAD

**Issue by mriccid** [drcmda/react-spring#239]
When interpolation occurs for a null value, an exception `TypeError entry.interpolation._interpolation is not a function` is thrown at line 144 of Spring.js. 

```
// Deal with interpolations
const previous =
    entry.interpolation &&
    entry.interpolation._interpolation &&
    entry.interpolation._interpolation(entry.animation._value)
```

I'm not sure if this is expected behaviour, but I would have thought it could either
- fail gracefully and warn, or
- skip the animation and instead just pass the value of `null` through to the child function.

This sandbox reproduces the bug: https://codesandbox.io/s/8lll45290l

Looking at the code snippet above, it seems odd that it expects to safely call the `_interpolation` function.

**Comment by drcmda** [comment]
The from-to type should always be the same. It would be good to have invariant checking in dev mode at some point, though.
