### ISSUE TITLE
Mapping an array for Trail throws an error

### ISSUE THREAD

**Issue by samrith-s** [drcmda/react-spring#24]
Hey guys,

First off, loved what you guys are doing with Spring. Looks very very promising! Now to the issue (☹️), I went through the examples and found `Trail` most suitable for my purpose.

My code for the Trail component is something like this:
```js
import React, { Component } from 'react';
import { Trail, config, animated, template } from 'react-spring';

import MoreInfo from '../../MoreInfo';
import RevenueBlock from './blocks/RevenueBlock';
import StatsBlock from './blocks/StatsBlock';

export default class TrailingComponent extends Component {
    state = {
        blocks: ['item-1', 'item-2', 'item-3']
    };

    getBlock = number => {
        switch (number) {
            case 1: {
                return <RevenueBlock />;
            }

            case 2: {
                return <MoreInfo />;
            }

            case 3: {
                return <StatsBlock />;
            }
        }
    };

    render() {
        const { blocks } = this.state;

        return (
            <div>
                <Trail
                    native
                    config={config.gentle}
                    from={{ opacity: 0, x: 100 }}
                    to={{ opacity: 1, x: 0 }}
                    keys={blocks.map(block => block)}
                >
                    {blocks.map((graph, index) => ({ x, opacity }) =>
                        <animated.div
                            style={{
                                opacity,
                                transform: template`translate3d(${x}%,0,0)`
                            }}
                        >
                            {this.getBlock(index + 1)}
                        </animated.div>
                    )}
                </Trail>
            </div>
        );
    }
}
```
The three blocks (`Revenue`, `MoreInfo`, `Stats`) are just `div` with nothing fancy in them.

Whenever `TrailingComponent` mounts, I get this error:
*A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.*
![image](https://user-images.githubusercontent.com/9032162/38697704-53a0f696-3eb0-11e8-8290-42dd679a1212.png)

Can you guys help me out on what I'm missing here?

**Comment by drcmda** [comment]
Could you dump that into a codesandbox? I’ll take a look then.

**Comment by samrith-s** [comment]
Hey @drcmda, here is the code: https://codesandbox.io/s/k01ym42kor

It seems to be working. I think I need to figure out what's happening in my application. As we are just returning divs. 

Would it be worth noting that we are using React 15 and not 16?

Also, if you check the codesandbox, when I set friction really low, the page flickers. Any idea why?

**Comment by samrith-s** [comment]
@drcmda Alright, thanks!

We are porting our app to R16 soon. Will let you know if we face the same issues!

As for the flicker, I was just testing it out, coz we have a tiny mini game which required physics. So was trying to use it there. Were adjusting the friction and tension based on how much you dragged a person and then let them go on different surfaces. :)

**Comment by ralphstodomingo** [comment]
@drcmda, Thanks for your hard work with this library! I find it really intuitive to use.
I just have a question about Trail and Transition. All examples use maps of some sort. How would an example look like if a raw array is used as the children of these primitives?
I can't seem to get it to work, always tells me `target.map is not a function`, but I make sure to return an array of functions.

**Comment by drcmda** [comment]
Both expect an array of functions as their children. If your state is an array already then that's easy, give it the keys

    keys={this.state.data.map(item => item.key}}

and the children:

    {this.state.data.map(item => props => <div style={props}>{item.text}</div>)}

Where `props` is the part that contains the animation values, just like in a regular spring.

If your data isn't an array but an object, it's similar, keys:

    keys={Object.values(this.state.objects).map(item => item.key)}

children:

    {Object.values(this.state.objects).map(item => props => <div style={props}>{item.text}</div>)}

**Comment by drcmda** [comment]
As for `target.map is not a function` ... this comes from Trails render function:

<img width="654" alt="screen shot 2018-04-23 at 13 35 02" src="https://user-images.githubusercontent.com/2223602/39124280-2b77eef6-46fb-11e8-8736-2596a52e66f4.png">

In other words, you didn't provide an array as Trails children, but something else.

**Comment by ralphstodomingo** [comment]
Thanks! I got it working for some reason when I made a separate array instead of returning an array directly in the render function/jsx.
Really intuitive, getting the hang of native keyframe animations.

**Comment by drcmda** [comment]
@ralphstodomingo good to hear! maybe console.log out the prior array for once, must be somthing very weird going on in it if it doesn't have the .map method, but good you solved it.

**Comment by joe307bad** [comment]
I am also getting an error for `target.map is not a function` and I can't seem to figure out the issue.

@ralphstodomingo would you mind posting the code that worked for you?

**Comment by drcmda** [comment]
@joe307bad could you link a codesandbox? i can take a look ...
