### ISSUE TITLE
Keyframes infinite animation doesn't work well with rerendering

### ISSUE THREAD

**Issue by ariesxje** [drcmda/react-spring#243]
I wanted to make an infinite animation that keeps going forever. The example uses `Keyframes` and set `reset` to `true`.
However, it always resets when the component gets re-rendered.
See the example below:
https://codesandbox.io/s/8lk3l18mo2

The animation looks broken because I have a `setState` called every 100 milliseconds. If you remove the `setInterval` inside the `componentDidMount` function, the animation went well.

You can't prevent the parent component from getting updated by state/props. Is there any other way to do infinite animation?

**Comment by drcmda** [comment]
That's what `reset` does though, it resets. The interval now causes it to reset more often. One way would be to remove reset and animate `to`: https://codesandbox.io/s/94173yryzr

**Comment by ariesxje** [comment]
Thanks for the reply.
Basically using math to create the infinite loop. I guess for animations of which the beginning and the ending do not continue, we have to reset the variable in the Keyframes.Spring.
To be honest, I think the reset option is a bit dangerous here, as it introduces interruption to animation from the update of the parent component.
Thanks.

**Comment by drcmda** [comment]
It's an escape hatch and due to the way it works it can be risky b/c if anything re-renders the component outwards it resets. It can be useful in situations where you want it to reset conditionally, but it's otherwise seldomly used.
