### ISSUE TITLE
Getting React.createRef() to work with react-spring

### ISSUE THREAD

**Issue by walmink** [drcmda/react-spring#245]
In pull request #185, ref forwarding was added to react-spring—yay!

### The problem
React-spring currently only handles ref forwarding if using the ["callback ref" method](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs). However, a newer method using [React.createRef()](https://reactjs.org/docs/refs-and-the-dom.html#creating-refs) is not supported. In this case, instead of a function, the ref retrieved via an object with the form `{current: [node]}`.

Discussion of the issue with error in [this Spectrum post](https://spectrum.chat/thread/ced06672-75c7-478a-89db-7d9983333001).

### Proposed solution
Handle both callback refs and React.createRef() in react-spring.

### Suggestion (please discuss)
In [createAnimatedComponent](https://github.com/drcmda/react-spring/blob/master/src/animated/createAnimatedComponent.js) on [line 71](https://github.com/drcmda/react-spring/blob/master/src/animated/createAnimatedComponent.js#L71), we could check whether the ref passed is a function or object and handle it accordingly:

```
<Component
  {...animatedProps}
  ref={node => {
    this.node = node
    if (forwardRef) {
      // If it's a function, assume it's a ref callback
      if(typeof forwardRef === "function")
        forwardRef(node)
      // If it's an object and has a 'current' property, assume it's a ref object
      else if(typeof forwardRef === "object" && forwardRef.current)
        forwardRef.current = node
      }
    }
  }
/>
```

**Comment by drcmda** [comment]
It's fine with me, could you test and see if it works? Then just add the PR and i'll merge right away.

**Comment by drcmda** [comment]
I added your code into the 6.x branch, it'll come out soon.

**Comment by walmink** [comment]
Thanks for putting it in!

I see you removed the check for whether `forwardRef.current` exists. Took me a moment but makes sense: it's better that it triggers an error instead of silently failing 👍

**Comment by drcmda** [comment]
It actually didn't work that way b/c initially ref.current is null, so that condition will always return false and never get to set it.
