### ISSUE TITLE
@babel/runtime errors

### ISSUE THREAD

**Issue by kaneel** [drcmda/react-spring#246]
Hi, 

On the current setup of a project I'm working on, we tried to add react-spring and stumbled upon an error at build.

While importing: 

```javascript
import { Spring } from "react-spring"
```
We get:
```
./node_modules/react-spring/dist/web.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/extends' in '/Users/kaneel/Documents/repos/mbox/proto/node_modules/react-spring/dist'
```

And while importing 

```javascript
import { Spring } from "react-spring/dist/web.cjs"
```
We get:
```
./node_modules/react-spring/dist/web.cjs.js
Module not found: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in '/Users/kaneel/Documents/repos/mbox/proto/node_modules/react-spring/dist'
```

webpack version: 4.8.3

Thank you for any inputs :)

**Comment by TrySound** [comment]
@kaneel Do you use create-react-app, next.js, yarn flat node_modules mode or babel runtime aliases in your setup?

**Comment by kaneel** [comment]
yep, rca indeed

**Comment by TrySound** [comment]
Try to upgrade it to 2.0. Its dependency resolving is quite weird relatively to babel runtime.

**Comment by penumbra1** [comment]
Hi, looks like some codesandbox examples are also affected, e.g. https://codesandbox.io/embed/yj52v5689

**Comment by drcmda** [comment]
CSB switched to babel 7 today, i think they must've broken something. This will cause a lot of issue for certain so i'm sure it's gonna be fixed soon. Unfortunately i've made lots of boxes without being logged in it seems, can't update them now. I plan to update all boxes once 6.x is out.

**Comment by kaneel** [comment]
@TrySound Well spotted, it was indeed because the project is based on RCA and after some updates (inc. peer dependencies), it finally worked. Thanks a lot!
