### ISSUE TITLE
IE11 / Browser Support

### ISSUE THREAD

**Issue by rmartin** [drcmda/react-spring#248]
**Issue:**
When loading the examples in the site they currently throw an exception in IE11: 
object doesn't support property or method 'assign'. 
Ex: https://yj52v5689.codesandbox.io/

**Potential Solution:**
I believe that this can be addressed by adding in the babel-polyfill to address this in general. I'm not clear if this would uncover additional bugs with IE11 that would also need to be addressed. 

**Documentation Update:**
Is it possible to add this and perhaps also add a browser support graph to the documentation to highlight what is expected to be supported with this framework?

**Marketing Site Note:**
Unrelated, the main site for http://react-spring.surge.sh/ fails to load at all in IE11 and does not throw a JS error.

**Comment by drcmda** [comment]
I think it needs polyfills. Could you try if babel-polyfill fixes it? I don't have IE11 available on my macbook right now. Would need to install some kind of VM.

**Comment by rmartin** [comment]
@drcmda Sure thing, i'll keep you posted on what I find.

**Comment by rmartin** [comment]
@drcmda This has now been addressed. It took a bit as we needed to have the supporting NPM module be published (https://github.com/christensson/babel-plugin-transform-es2017-object-entries/issues/2) and had issues with GitHub from last weekend. I've validated this within Browserstack using the base fade-in example in a separate project. 

**Future Enhancement**
I believe that a future enhancement would be to add a 'supported browsers' grid similar to the one that does the feature comparison. If you think that would be valuable, let me know and I can create a test that will include all of the relevant features and make sure that they are working as expected and do a more exhaustive browser test for those in a separate issue. 

Let me know if there is anything else that I can do to help. By merging this in it will allow us to use this in a few upcoming projects. Thanks so much for all your effort on this!

**Comment by vai0** [comment]
Has this fix already been merged into master? I'm still encountering issues with `entries` not being supported on IE11 with version 6.1.6

**Comment by dotlouis** [comment]
Same here, Object.entries not supported. I had to add it manually for it to work on IE11

**Comment by drcmda** [comment]
There is now a section in the docs describing this: https://github.com/drcmda/react-spring/issues/330 just need to build docs and publish. I think the general idea is to offload polyfills onto the end user, because it would otherwise stretch bundle size and affect performance in a bad way.

**Comment by dotlouis** [comment]
I agree, polyfills should not be included by default for a lib. It allows the end user to customize for its particular needs. But the doc should help regarding what polyfills could be needed. Thanks for #332 :)
