### ISSUE TITLE
Animation duration?

### ISSUE THREAD

**Issue by btmdave** [drcmda/react-spring#25]
Great library, but when using Transition w/ Animated is there a way to control the duration?

**Comment by drcmda** [comment]
Funny that you ask, i just merged it:

https://codesandbox.io/s/q9lozyymr9

https://github.com/drcmda/react-spring/tree/master/src/addons

The lib normally focusses on spring based animation as it makes fluid interfaces far more easy to write. But now you can exchange the underlying implementation.

It's not documented yet, but the examples makes it clear how to use.
