### ISSUE TITLE
Animating while using plain routes?

### ISSUE THREAD

**Issue by A7DC** [drcmda/react-spring#252]
Hi everyone! Has anyone got an example of animating [plain routes?](https://l.messenger.com/l.php?u=https%3A%2F%2Fgithub.com%2FReactTraining%2Freact-router%2Fblob%2Fv3%2Fdocs%2Fguides%2FRouteConfiguration.md%23configuration-with-plain-routes&h=AT0ppgPW1R44lSBgUo0XnP61bmi5FNlSOAw0QVwc0FGIK2gQS63TAoeAF2ExQfK5NfvgETM1BfwnRpcJW7AXFTUhtCgTKRnyveTcKOW-Wb2KD3UqyOThz1anDD9pxWpACIu3RQSWj54ZbL_X7wAZ5wMuEiU)

Here's some example code of what I mean:

```
import React from "react";
import ReactDOM from "react-dom";
import { hashHistory, Router, Route, Link } from "react-router";

// components
import Home from "./components/Home";
import About from "./components/About";

const App = ({children}) => (
  <div>{children}</div>
)

const routes = {
  path: "/",
  component: App,
  indexRoute: { component: Home },
  childRoutes: [{ path: "about", component: About }]
};

const root = document.getElementById("root");
ReactDOM.render(
  <Router history={hashHistory} routes={routes} />, 
  document.body)
```

I'm not sure how you'd do it if you're not using JSX. Is this even possible? 

[Codesandbox](https://codesandbox.io/s/31y4kqmq81)

**Comment by drcmda** [comment]
Haven't used plain routes before, but i think something like this would do: https://codesandbox.io/embed/p5w77z66jq

**Comment by A7DC** [comment]
As always, so helpful. Thanks Paul! 🙏

**Comment by A7DC** [comment]
Hey @drcmda, unfortunately I'm using [an older version of react and router](https://codesandbox.io/s/kwx9o301n3), so changing the versions I get the following error:

```
TypeError
React.forwardRef is not a function
```

I'm assuming this is something to do with the react-spring version. Any ideas?

**Comment by drcmda** [comment]
I think react didn't have that feature previously. That would be tough to solve since i wouldn't know how to polyfill it.
