### ISSUE TITLE
Slight modification to examples/demos/reveals breaks animation

### ISSUE THREAD

**Issue by ivandurst** [drcmda/react-spring#253]
The original example works well: https://codesandbox.io/embed/yj52v5689

But when I move the `animated.div` component inside of the `render` function so that the `pages` data looks more like real-world data, the animation breaks: https://codesandbox.io/s/ryn8p5xxp 

I tried adding `force`, but to no avail. Is this a bug or intentional, and can you provide an example that uses data similar to what would be retrieved from an API? Thanks!

**Comment by drcmda** [comment]
It can't distiguish between items/keys that way. If you pass its a key it's fine.

```jsx
        <Transition
          native
          keys={this.state.index}
```

**Comment by ivandurst** [comment]
Works great, thanks!
