### ISSUE TITLE
TypeError props.children is not a function

### ISSUE THREAD

**Issue by snydercreative** [drcmda/react-spring#254]
I love the demos, but I can't get Trail to work. I keep getting an error trying to use Trail on Semantic UI list items. Here's the sandbox showing the error. I'm sure I'm doing something wrong here, but I can't figure out what it is. 

https://codesandbox.io/s/r5loxqr2kp

Thanks in advance :)

**Comment by drcmda** [comment]
The box doesn't seem to have any datasource to display. There's also a small error in how you treat Trail children. Trail accepts an array of functions, in other words:

```jsx
<Trail>
  {branches.map(branch => animatedStyles => <div style={animatedStyles)>{branch}</div>
```

https://codesandbox.io/s/yq978xyjy1

**Comment by snydercreative** [comment]
Thanks for the quick response!
