### ISSUE TITLE
Transition won't play when change functions defined in a loop 

### ISSUE THREAD

**Issue by rozd** [drcmda/react-spring#256]
I'm not sure if it is an issue or misunderstanding from my side, but I can't play transition when its change functions `style => React.Component?` defined in a loop. 

To reproduce this issue slightly modified Reveals example https://codesandbox.io/embed/yj52v5689 with dynamically generated `pages` array like this:

```javascript
let letters = [
  { symbol: 'A', color: '#247BA0' },
  { symbol: 'B', color: '#B2DBBF' },
  { symbol: 'C', color: '#12DBBF' },
];

let pages = [];
for (let i = 0; i < letters.length; i++) {
  pages.push(style => <animated.div style={{ ...style, background: letters[i].color }}>{letters[i].symbol}</animated.div>);
}
```

after that Transition stops animate mount/unmount after first page, here is a complete project that reproduce this issue – https://codesandbox.io/s/6nvzj93pw3

Thank you in advance.

**Comment by drcmda** [comment]
It needs keys: `keys={this.state.index}`, see: https://github.com/drcmda/react-spring/issues/253

**Comment by drcmda** [comment]
In 6.x i have made this more obvious btw.

**Comment by rozd** [comment]
Works perfect. Thank you! 😃

Sorry for duplicate issue, I didn't guess to search with `Reveal` keyword.
