### ISSUE TITLE
React Native Documentation

### ISSUE THREAD

**Issue by muraterd** [drcmda/react-spring#258]
The "React-native and other targets" link is broken in the readme file. I want to use this library for react native but couldn't figure out. Can someone help me pls?

**Comment by drcmda** [comment]
It's here now: http://react-spring.surge.sh/ just scroll down a little. I am currently re-doing documentation for this. Basically it works the same, you import react-spring as is, and wrap your native componentns (View, Text, etc) in animated (`const AnimatedView = animated(View)`).
