### ISSUE TITLE
Ability to animate container size changes?

### ISSUE THREAD

**Issue by LordZardeck** [drcmda/react-spring#260]
I feel like what i'm asking is crazy, but maybe someone else can lead me on the right path. I have a container element centered on the page. The height and width are determined by the children. Initially i have a larger child, but then transition out that react-spring's 2-state transition. Everything animates well enough. The problem is, once that larger child is finally removed from the dom, the container element "snaps" to a smaller size. I was hoping there was a way to have the width and height animate to the smaller size. As far as I can tell, there's no way to do that with pure CSS. Is it possibly that react-spring could somehow magically do that? If not, what's the suggested way?

**Comment by drcmda** [comment]
Hard to do anything without something to toy with, a codesandbox with your example really is the best way to figure out solutions. From how it sounds it's probably some css related thing and i guess it would be easy to solve.
