### ISSUE TITLE
Position Fixed

### ISSUE THREAD

**Issue by joshperrin** [drcmda/react-spring#261]
When doing any animation, the container contains a transform property of translate3d(0%, 0%, 0px).

This renders any children of the container unable to use position fixed. As position fixed turns relative to the container if the container contains a transform.

Would it be possible to remove the transform property after animating?

**Comment by drcmda** [comment]
In the 6.x beta there's a "after" field that allows you to apply props after an animation is through. Is this what you want to do?

**Comment by joshperrin** [comment]
Yeah, that sounds like it would work.

Can I use it now? How would I go about using the beta and the after property?

thanks!!

**Comment by joshperrin** [comment]
Tried using 6.x beta, and Keyframes.Spring seems to be missing. Is there a new way to create Keyframes? Is 6.x close enough to start using?

**Comment by drcmda** [comment]
What does console.log(Keyframes) say? Keyframes is mostly the same, the only thing that changed is that you don't need `to: {...}` any longer, you can just drop props in there, but it's backward compatible. I think you can start playing with the beta, the api choices are fixed now. I am almost done, there will be a TON of updates and new features, just fixing the last of the old examples that refuse to work, then writing some docs. I plan to release it 25th oct.

**Comment by joshperrin** [comment]
I think the issue was I was on an older version of the beta. 
On Beta.5 I'm getting the error:

`TypeError: child is not a function
    at Object.children (modules.js?hash=f35153624778d861d402e2d4830b95df801a0299:40687)
    at renderChildren (modules.js?hash=f35153624778d861d402e2d4830b95df801a0299:39075)
    at Spring.render (modules.js?hash=f35153624778d861d402e2d4830b95df801a0299:39971)
    at finishClassComponent (modules.js?hash=f35153624778d861d402e2d4830b95df801a0299:16944)
    at updateClassComponent (modules.js?hash=f35153624778d861d402e2d4830b95df801a0299:16907)
    at beginWork (modules.js?hash=f35153624778d861d402e2d4830b95df801a0299:17496)
    at performUnitOfWork (modules.js?hash=f35153624778d861d402e2d4830b95df801a0299:19822)
    at workLoop (modules.js?hash=f35153624778d861d402e2d4830b95df801a0299:19860)
    at renderRoot (modules.js?hash=f35153624778d861d402e2d4830b95df801a0299:19939)
    at performWorkOnRoot (modules.js?hash=f35153624778d861d402e2d4830b95df801a0299:20793)`

**Comment by drcmda** [comment]
Could you paste the code snippet? Maybe it's relevant for the new version as well.

**Comment by drcmda** [comment]
after is normally for springs, on transitions im not sure how it could make sense, doesn't it conflict with from/enter/leave? If you set transform to "none" after enter, and then to "translate3d(105%,0,0)" on leave it would (well, ...should) crash since it can't interpolate "none" to that 3d translate.

but either way, it probably shouldn't behave like it does in your sandbox. it luckily avoids the crash that should happen due to some internals.

**Comment by joshperrin** [comment]
Yeah, you're right, on the leave you would want it to animate from the enter state, not the after state. I'm not really sure if this is feasible or not.

It's just a fairly common use-case where you would animate a panel in and out of the UI. But in order to use position fixed inside of this panel, you need to set the transform to none, in order for position fixed to work properly.

Maybe the best solution is to not use a Transition. Unless you have any other ideas. Does the after prop work on Keyframes?

**Comment by drcmda** [comment]
I think keyframes causes after to not work here actually because transition is driven by it internally. Need to inspect it a little more.
