### ISSUE TITLE
render() being called without getDerivedStateFromProps() causes endless loop

### ISSUE THREAD

**Issue by onnlucky** [drcmda/react-spring#262]
If `getDerivedStateFromProps()` calculates `propsChanged` to `true`. And `render()` gets called it might end up in an endless `setState()` loop. Specifically, when the loop doesn't go past `getDerivedStateFromProps()` again. Which depends on how parent elements behave, if they do `setState()` etc.

There are two solutions as far as I can see:
1. the new `AnimatedProps` object uses a callback for `setState()` should work to always do `propsChanged: true` in there.
2. (better) don't use the react lifecycle for concerns within a single cycle. Make `propsChanged` a field, set in `getDerivedStateFromProps()` if needed; unset after `render()` has seen and dealt with it.

**Comment by drcmda** [comment]
Do you have a codesandbox that causes this loop?

**Comment by onnlucky** [comment]
I tried reducing the case to a codesandbox, but the actual combination of things escapes me, I'll try to bundle a small-ish case that triggers it in our environment.

This is about Frame X, which indeed ships with react 16.2 for now. But I've upgraded it to 16.5.2 and we were still hitting this issue.

But you are correct, React documentation says `getDerivedStateFromProps()` is called before **every** render, and that also seems the be the case (contrary what I had assumed, and what was the case < 16.4, namely called after a parent `render()`).

Still, I would not recommend using `setState()` for intra-lifecycle concerns.

**Comment by drcmda** [comment]
The problem is that it goes through multiple render stages in order to calculate "auto" and possibly other values in the future. If it had the capability to render, measure, then render again without causing setState that would be lovely but i don't think react can do this. But if the issue is somewhere reproducable where i can inspect it i'll fix it right away.

**Comment by onnlucky** [comment]
Ah, that makes sense. Though `componentDidMount` and `componentDidUpdate` can fill in the right data, then drive a second cycle via (an empty) `setState()`, and otherwise try to be as idempotent as possible.

The thing is, solving this auto value concern you mention requires state, but not state in the sense of how react uses `this.state` imho. Because clearing the state would require yet another cycle, or fragile code that prevents any future cycle to not act upon the lingering state.

**Comment by onnlucky** [comment]
Thank you for your time. It did turn out to be that older react issue, but there were two versions running on the page, with the newer version loading user components, the older version driving lifecycles :(

I'll close this issue, thanks.
