### ISSUE TITLE
Clarify documentation "Individual Transitions" on Transition Component For List Items

### ISSUE THREAD

**Issue by jwdinker** [drcmda/react-spring#268]
Hey there.
In the documentation for the Transition Component it says "For more complex transitions you can return per-item values individually."  

It seems that if you pass in an array of items, the from, enter, and leave only get called for the first item in the array.  I didn't know if this is expected, as I am coming from react-motion where you can change the values based on the item key.  So my question is...

If you are transitioning more than 1 item in a list, do these per item values only apply to the whole list not each individual transitioning child? 

```javascript
 const items = [
    {
      key: 'overlay',
      component: Overlay,
      from: { opacity: 0 },
      enter: { opacity: 1 },
      leave: { opacity: 0 },
    },
    {
      key: 'dialogue',
      component: Dialogue,
      from: { opacity: 0, transform: 'scale(0)' },
      enter: { opacity: 1, transform: 'scale(1)' },
      leave: { opacity: 0, transform: 'scale(0)' },
    },
  ];

  return (
    <Transition
      native
      keys={(item) => item.key}
      items={items}
      from={(item) => {
        console.log('FROM ITEM: ', item);
        return { opacity: 0 };
      }}
      enter={{ opacity: 1 }}
      leave={{ opacity: 0 }}>
      {(styles) =>
        items.map((item) => {
          const Component = item.component;
          return (
            <animated.div key={item.key} style={styles}>
              <Component />
            </animated.div>
          );
        })
      }
    </Transition>
  );
```

![2018-10-19_15-51-04](https://user-images.githubusercontent.com/2313028/47243254-0cade900-d3b7-11e8-83a2-92e03c05cc27.png)

**Comment by drcmda** [comment]
Whatever this was, it shouldn't be. I just tried this in the 6. beta and it looks good: https://codesandbox.io/s/zxr3wo6x5l

I am putting more effort in making docs, sitting on it right now - otherwise i could release.

**Comment by drcmda** [comment]
Docs are out, your example should work in 6.0.

**Comment by jwdinker** [comment]
@drcmda Thanks, Paul!  I'll give it a go.  I appreciate the prompt turn around.
