### ISSUE TITLE
Thanks for creating and maintaining this project!

### ISSUE THREAD

**Issue by joshwcomeau** [drcmda/react-spring#269]
Just wanted to share my appreciation to @drcmda and the 38 other contributors - this project is amazing and has saved me a ton of time. Really thankful that it exists :)

I got the idea to create this issue from https://changelog.com/posts/make-an-open-source-maintainers-day-with-this-one-weird-trick

(feel free to close, since this isn't a real issue :D)

**Comment by drcmda** [comment]
This means a lot to me, thanks! Been struggling over the last weeks with rewrite and there were some dark moments and doubts. This is a lovely reminder to me that it's not in vain. 😄
