### ISSUE TITLE
tiny import issue in one of the example demos

### ISSUE THREAD

**Issue by tinacho** [drcmda/react-spring#27]
I just wanted to check out the animation and ran accross this issue while compiling 
```javascript
ERROR in ./demos/sunburst/index.js
Module not found: Error: Can't resolve './Partition' in '.../react-spring/examples/demos/sunburst'
 @ ./demos/sunburst/index.js 10:0-36 101:27-36
 @ ./demos lazy ^\.\/.*$ namespace object
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 index.js
ℹ ｢wdm｣: Failed to compile.
```
It's basically just a typo in this import from Sunburst demo:
`import Partition from './Partition'`

Uppercase instead of the lowercase `P` in `... from './Partition'`

**Comment by drcmda** [comment]
Strange, it's uppercase in my local repo, but lower on Github. Have to Google this, never came across something like it before.

**Comment by drcmda** [comment]
`git config core.ignorecase false` did it, it's updated now ... Thanks!

**Comment by techniq** [comment]
you could also use:
```js
import { Partition } from '@vx/hierarchy'
```
if you wanted
