### ISSUE TITLE
TransitionItemProps Types

### ISSUE THREAD

**Issue by iranana** [drcmda/react-spring#275]
Hi, thank you for maintaining and publishing such an awesome library! Hopefully this issue hasn't been raised before (and hopefully I'm not just being stupid).

I'm using TypeScript in my project, and noticed that TransitionItemProps may be a string, number or object (https://github.com/drcmda/react-spring/blob/master/index.d.ts#L128).

However, I noticed the docs mentions that this can be `any`, and the PropTypes seem to indicate this too (https://github.com/drcmda/react-spring/blob/master/src/Transition.js#L55, http://react-spring.surge.sh/transition).

I'm toggling the visibility of a modal based on a boolean flag (modal mounts/unmounts on route change). Maybe I'm doing something weird and this isn't how `items` is meant to be used, but here is an example that roughly shows what I'm attempting to do. TypeScript fails to compile this based on the type of `items`.

https://codesandbox.io/s/v0xnxy3060

Thank you in advance!

**Comment by drcmda** [comment]
I guess this is related to: https://github.com/drcmda/react-spring/issues/276 Could you see if that's the case?

**Comment by iranana** [comment]
Thanks for the reply :) From what I can tell the types I have locally are the most up to date, and the types in the master branch and 6.x.x are all in line. Assuming that items/TransitionItemProps may been a boolean, perhaps it was just an oversight when the types were being written?

**Comment by drcmda** [comment]
It can well be. If you know how to fix it (i don't unfortunately :-( ... ) could you make a PR?
