### ISSUE TITLE
documentation suggestions

### ISSUE THREAD

**Issue by cusxio** [drcmda/react-spring#290]
I have a few questions that aren't answered by the documentation but eventually managed to figure it out. After reading/trying it out a few times.

So here are some suggestions that I believe will improve comprehension for **new users**.

1. `animated` and `native` needs to be used together. This piece of information needs to be on the [`prop page`](http://react-spring.surge.sh/spring) for `native`.

While reading the doc, the constant question I have is, what is `animated` ?

The only place where this is mentioned is on the [`perf page`](http://react-spring.surge.sh/perf). The `perf page` is somewhat "hidden", i.e. the last place someone new to the library will read.

**Unrelated**: I realised that not all property are supported by `native` ? i.e. `background` ?

--- 

2. The `config` prop needs to be clarified better. 

While reading, I noticed that the `config` prop allows easing, but at the same time allow physics based configuration. So my first impression is "What's happening?"

It is only later on the [gotchas](http://react-spring.surge.sh/gotchas) page that I understand what's happening.

---

3. The documentation should list [the exports](https://github.com/drcmda/react-spring/blob/master/src/targets/web/index.js#L156-L167) of the library to let users know what can be done/ or not done.

**Comment by drcmda** [comment]
All good suggestions. I must say i am struggling a little with proper english and writing docs in general. Would you be up for a PR? It's all under /documentation/*.mdx, simple markdown files with some components mixed in.

> Unrelated: I realised that not all property are supported by native ? i.e. background ?

native supports all styles and attributes, background works, too. Just tried it too and seems fine to me, do you have a snippet that i could inspect?

**Comment by cusxio** [comment]
> Would you be up for a PR? I would be so happy if someone with a better grasp for structuring could take a look at this.

Yea sure, I can take a stab at it.

> Do you have a snippet that i could inspect? https://codesandbox.io/s/9z766oxwvp

My bad. I reported the wrong thing.

It's the `transform` property that is not working for me.

- Here's an example **without** `native`:

https://codesandbox.io/s/628478kx5r

- Here's an example **with** `native`:

https://codesandbox.io/s/l93o2m5067

The transform `-40px` doesn't seem to apply on `native`

**Comment by drcmda** [comment]
Ah, that's an easy fix, it needs to be:

    transform: styles.y.interpolate(y => `translate3d(0px, ${y}px, 0px)`) 

Explained here: http://react-spring.surge.sh/perf#interpolation

But see, that's exactly the kind of stuff i have problems putting into understandable terms and structure. What native really does is spit out Objects instead of plain values. These objects receive updates. That is why you need animated.el, it knows how to deal with these animated-objects.

**Comment by cusxio** [comment]
ah I see. Thanks for all the information. Really appreciate it. 

So that's the behaviour of `native`.

I guess this leaves me to the next logical question. Why isn't `native` the default?

**Comment by cusxio** [comment]
👌 Thanks again. I'll see what I can do about the docs. English is not first language too, but what I can offer is my fresh perspective on the documentation as a beginner.

**Comment by ooloth** [comment]
@drcmda Love this library! Thanks so much for it. But also running into confusion when using `native`...

> Ah, that's an easy fix, it needs to be:
> `transform: styles.y.interpolate(y => `translate3d(0px, ${y}px, 0px)`)`

Does this mean that when using `native`, all numerical values need to be applied using `interpolate` (rather than just `style={props}`?

**Comment by drcmda** [comment]
Only if you need to interpolate (transform) values in any way. These aren’t numbers, they’re self updating objects that react otherwise couldn’t understand, that’s why you need animated.element.

**Comment by ooloth** [comment]
> Only if you need to interpolate (transform) values in any way.

Sorry if this is a stupid question: how do I know which values need to be interpolated/transformed and which don't?

**Comment by drcmda** [comment]
If you can use *values as they are*, you don't need to worry about anything:

```jsx
to={{ opacity: 0, transform: 'translate3d(10px,0.0)', color: 'blue' }}>
  {props => <animated.div style={props} />}
```

If you are using values that you shape into something else, you interpolate:

```jsx
to={{ something: 10, color: 0.75 }}>
  {props => <animated.div style={{
    transform: props.something.interpolate(x => `translate3d(${x}px,0,0)`,
    color: props.color.interpolate({ range: [0,1], output: ['red', 'blue'] })
  }}>}

**Comment by ooloth** [comment]
Interesting! Thanks for the thorough reply.

That demo is incredible, by the way. 👏

Just so I understand, when you say interpolating is "a tiny bit faster", do you mean it results in (slightly) better performance? I'm trying to understand if I should interpolate whenever I can (similar to using `native` whenever possible), or if the difference isn't noticeable. 

I prefer the shorter syntax of your first code example but will adopt whatever approach results in the smoothest performance. 

Your library is sweet and I want to use it properly. :)

**Comment by drcmda** [comment]
Upfront interpolation has a small tax since it has to regexp the hell out of these strings to extract numeric data from it, but it isn’t that much.
