### ISSUE TITLE
force prop breaks leave animation

### ISSUE THREAD

**Issue by carrickjason** [drcmda/react-spring#292]
I am using `Transition` to animate the height of accordion children to 'auto'.  I can have nested accordions so I need the `force` prop so that the parent accordion child will update when a nested accordion expands.  However, this seems to breaking when animated to the `leave` state.  I have replicated in a codesandbox [here](https://codesandbox.io/s/ql6pp05779).

**Comment by drcmda** [comment]
I’ll take a look

**Comment by drcmda** [comment]
It looks like "force" is interacting in a weird way with transition, which internally uses keyframes until it ends up on the spring. I guess it wasn't built for this.

Are you 100% certain transition is the primitive you want? A spring in your scenario has the upside of being smaller overhead and it won't re-mount contents which is faster. Springs also play nice with force: https://codesandbox.io/s/n54k8z9340

**Comment by carrickjason** [comment]
Hey, thanks for taking a look.  I'll try doing this with react-measure and Spring instead.

**Comment by carrickjason** [comment]
For anyone else who comes across this, I was able to find a nice solution using `react-measure` and `Spring`.  My `Expandable` component looks like this.  It handles nested `Expandable`s nicely. Thanks @drcmda for the recommendation.

```jsx
const Expandable = ({
  children,
  className,
  config,
  element,
  expanded,
  ...rest
}) => {
  const Component = element

  return (
    <Measure offset margin>
      {({ measureRef, contentRect: { offset, margin } }) => (
        <Spring
          native
          from={{ height: 0 }}
          to={{
            height: expanded ? offset.height + margin.bottom + margin.top : 0
          }}
          config={config}
        >
          {style => (
            <animated.div style={{ overflow: 'hidden', ...style }} {...rest}>
              <Component style={{ overflow: 'auto' }} ref={measureRef}>
                {children}
              </Component>
            </animated.div>
          )}
        </Spring>
      )}
    </Measure>
  )
}
```

**Comment by drcmda** [comment]
Hey, thanks and i'm glad it worked out! I think i'll use this in the docs and maybe remove force. Is there a codesandbox i could inspect?

**Comment by carrickjason** [comment]
Hey, I saw this and then forgot.  Anyways, here is an updated codesandbox https://codesandbox.io/s/xlkk6rkx3z
