### ISSUE TITLE
shallowEqual in web.js breaks if comparing two numbers and the project also uses prototypeJS

### ISSUE THREAD

**Issue by Zneider** [drcmda/react-spring#293]
I use React-Spring version ^6.0.0

I have a Spring that takes from={x: 0} to={x: -1} and sometimes it breaks when comparing two numbers. The stacktrace points to the code part below.

```
function shallowEqual(a, b) {
  if (typeof a !== typeof b) return false;
  if (typeof a === 'string') return a === b;
  var i;

  for (i in a) {
    if (!(i in b)) return false;
  }

  for (i in b) {
    if (a[i] !== b[i]) return false;
  }

  return i === void 0 ? a === b : true;
}
```

it seems that prototypeJS adds a prototype to the Number object called toColorPart. [http://api.prototypejs.org/language/Number/]
This causes "if (!(i in b)) return false;" to throw an exception if comparing two numbers.

The usage of prototypeJS is out of my hands, so would be great if you could somehow make a fix for this.

the code below shows the problem
```
Number.prototype.toColorPart = function(){return}
var car = 0;
for(i in car){
 console.log(i) 
}

try{
console.log('toColorPart' in car);
} catch(e){
 console.error(e) 
}
```

**Comment by drcmda** [comment]
oh my, this is brutal. could you paste a small reproduceable snippet where an object with that prototype extension causes problems with shallowEqual?

**Comment by Zneider** [comment]
Yes - this will reproduce the issue:
```
Number.prototype.toColorPart = function() { 
    /* do whatever */
    console.log('number proto');
}

function shallowEqual(a, b) {
  if (typeof a !== typeof b) return false;
  if (typeof a === 'string') return a === b;
  var i;

  for (i in a) {
    if (!(i in b)) return false;
  }

  for (i in b) {
    if (a[i] !== b[i]) return false;
  }

  return i === void 0 ? a === b : true;
}

shallowEqual(0,0);
```

**Comment by drcmda** [comment]
nice, would you forward this as a PR? i make you a patch release

**Comment by Zneider** [comment]
created a PR

**Comment by drcmda** [comment]
It's live under 6.1.5, thanks!
