### ISSUE TITLE
dark mode / design suggestion

### ISSUE THREAD

**Issue by ThomasRoest** [drcmda/react-spring#295]
First of all, thanks for all the work and maintaining this. 

I'm not a big fan of the dark mode docs design, there are some contrast issues (e.g. the pink highlights) And It's not very easy on the eyes. What do you think of this suggestion with a white background?

<img width="1265" alt="image 2018-10-30 at 9 30 55 pm" src="https://user-images.githubusercontent.com/4428811/47748700-b7fa5000-dc8b-11e8-931a-a7a43becb6e8.png">

**Comment by drcmda** [comment]
I thought so, maybe a little over the top. I had it like that for a while then switched to dark. If you like you can fork the repo, run yarn docz and edit ./doczrc.js and documentation/resources/Codemirror.js to make a variant or eventually a PR.

**Comment by drcmda** [comment]
Is this better? http://react-spring.surge.sh

**Comment by ThomasRoest** [comment]
yes much better I think!
