### ISSUE TITLE
Data not updating correctly

### ISSUE THREAD

**Issue by SugariuClaudiu** [drcmda/react-spring#297]
Hello,

I have come across an issue, where updating your data (like from your redux store) is not working and the component remains in the enter state.
Not sure if this is the right approach, but doing
```diff
+ item,
```
on https://github.com/drcmda/react-spring/blob/master/src/Transition.js#L153
seems to solve the issue.
It is simply updating the item on the current object.
If necessary, I'm happy to create a codepen or open a PR later today.

**Comment by drcmda** [comment]
Oh, looks like you're right, good catch! Please do make a PR, i'll make a patch release for this.

**Comment by drcmda** [comment]
It's published
