### ISSUE TITLE
react-native support?

### ISSUE THREAD

**Issue by stevoland** [drcmda/react-spring#3]
Hi, thanks for the library, the demos look fantastic.

We plan on building cross-platform components and are looking at animating solutions. Would it be feasible for this project to support react-native? Do you have ideas for an approach? Would you be interested in PRs towards this?

Thanks

**Comment by drcmda** [comment]
@stevoland rn would most certainly be possible, since animated supports it. I removed react-native.js from animated/targests but if put back it should be fine. 

PRs are welcome.

**Comment by Hamatek** [comment]
anyone managed to make it work with RN ?

**Comment by MarcelBlockchain** [comment]
+2

**Comment by smooJitter** [comment]
What do you mean by “I removed react-native.js”

**Comment by drcmda** [comment]
I think it would only be a matter of a few polyfills (request/cancelAnimationFrame) and adding View/Image/etc animated components under /arc/animated/targets/react-native. But i don't have the capacity right now and i haven't done much in RN. If anyone wants to give it a go - i could provide some guidance on project structure.

**Comment by drcmda** [comment]
Anyway, i had some free time today - it's looking good so far. You can try it out:

```jsx
import React from 'react'
import { StyleSheet, Text, View, TouchableWithoutFeedback } from 'react-native'
import { Spring, animated } from 'react-spring/dist/react-spring-native.esm'

const styles = {
    flex: 1,
    margin: 0,
    borderRadius: 35,
    backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
}

export default class App extends React.Component {
    state = { flag: true }
    toggle = () => this.setState(state => ({ flag: !state.flag }))
    render() {
        const { flag } = this.state
        return (
            <Spring native from={{ margin: 0 }} to={{ margin: flag ? 100 : 0 }}>
                {props => (
                    <TouchableWithoutFeedback onPressIn={this.toggle}>
                        <animated.View style={{ ...styles, ...props }}>
                            <Text>It's working!</Text>
                        </animated.View>
                    </TouchableWithoutFeedback>
                )}
            </Spring>
        )
    }
}
```

![rn](https://user-images.githubusercontent.com/2223602/40568285-0f4959ca-607a-11e8-99e7-e6bf61f83121.gif)

**Comment by drcmda** [comment]
Never mind, colors work - must've been the emulator, on my iphone it's fine. So to me it looks like all behaves as it should be. I'll run some tests and it will be available under `react-spring/dist/native` in the next release.

**Comment by drcmda** [comment]
@stevoland @Hamatek @MarcelBlockchain @smooJitter are there any things to watch out for now? For instance, in the dom we use animated.div animated.h1 and so on, it's basically just a list of strings, but in RN if i wanted to pull all the available primitives (View, Text, Image, ........) --- these are real classes, and it would pull down bundle-size. Would RN users be ok if i don't expose "animated" and instead you create your own primitives using `createAnimatedElement` like so:

```jsx
import { Spring, createAnimatedComponent } from 'react-spring/dist/native'
import { View } from 'react-native'

const AnimatedView = createAnimatedElement(View)

<Spring ...>
    {props => <AnimatedView ... />}
</Spring>
```

?

**Comment by drcmda** [comment]
Released it: 5.3.1: https://twitter.com/0xca0a/status/1000513216672403456

Goes actually further than react-native, it could animate all platforms now.

**Comment by smooJitter** [comment]
Whoa....  I will take a look in a few days.  I'm traveling for the holiday.

**Comment by smooJitter** [comment]
I will take a look in a few days.  I'm traveling right now.

**Comment by a-m-dev** [comment]
whats up guys ??? any production level examples ????

**Comment by JamieCorkhill** [comment]
Is `react-spring` now capable to be used with React Native? Did this go anywhere?

@a-m-dev @drcmda Have you heard anything?

**Comment by brunolemos** [comment]
> any production level examples ?

> Is there a repo or any examples with RN?


DevHub uses it on iOS, Android and web: https://github.com/devhubapp/devhub

Works great.

**Comment by JamieCorkhill** [comment]
@brunolemos 

Thank you. Is it just used from this repo out-the-box or is extra configuration required? Perhaps the repo you linked will show how it's done.
