### ISSUE TITLE
Simple example. Typescript error?

### ISSUE THREAD

**Issue by glebkudr** [drcmda/react-spring#300]
Could you please provide a small example of working with this library with Typescript?

Like, I want to use this in my render function:

```
    <Spring
      from={{ opacity: 0 }}
      to={{ opacity: 1 }}>
      {props => <div style={props}>hello</div>}
    </Spring> 
```

It causes Typescript type errors and I don't know how to solve it :( Apparently there should be a way to work with this on Typescript since there are definitions etc. But I can't figure how. 

```
Type '{ children: (string | ((p: {}) => Element))[]; from: { opacity: number; }; to: { opacity: number; }; }' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Spring<{}, {}>> &
Readonly<{ children?: ReactNode; }> & Readonly<SpringProps<{}, {}>>) | (IntrinsicAttributes & IntrinsicClassAttributes<...> & Readonly<...> & Readonly<...>)'.
  Type '{ children: (string | ((p: {}) => Element))[]; from: { opacity: number; }; to: { opacity: number;
}; }' is not assignable to type 'Readonly<SpringProps<{ children: (string | {})[]; from: { opacity: number; }; to: { opacity: number; }; }, { opacity: number; }> & { children: (string | {})[]; from: { opacity: number; }; to: { opacity: number; }; }>'.
    Types of property 'children' are incompatible.
      Type '(string | ((p: {}) => Element))[]' is not assignable to type 'SpringRendererFunc<{ children: (string | {})[]; from: { opacity: number; }; to: { opacity: number; }; }, { opacity: number; }> & (string | {})[]'.
        Type '(string | ((p: {}) => Element))[]' is not assignable to type 'SpringRendererFunc<{ children: (string | {})[]; from: { opacity: number; }; to: { opacity: number; }; }, { opacity: number; }>'.
          Type '(string | ((p: {}) => Element))[]' provides no match for the signature '(params: { opacity: number; } & { children: (string | {})[]; from: { opacity: number; }; to: { opacity: number; }; }): ReactNode'.
```

**Comment by drcmda** [comment]
There was just a new PR that i merged yesterday, hopefully it fixes it. All TS types for this lib are done by contribution (since i myself don't use/know TS). I released it under react-spring@6.1.7-beta.2 could you try if that makes it better?

**Comment by glebkudr** [comment]
My bad, I found an issue and it wasn't a bug. You should place **props** in brackets & specify type: any & place function body part in brackets too. So now it is (props:any)=>(some jsx) and it is no error in Typescript. 

May be it will be a good idea to add this note in examples for TS users.

This works:
```
<Spring
  from={{ opacity: 0 }}
  to={{ opacity: 1 }}>
  {(props:any) => (<div style={props}>hello</div>)}
</Spring>
```

**Comment by drcmda** [comment]
Would you make a PR for a "Types" page in the docs? Like i said, i don't know TS much to be able to document it. Gonna close the issue here, but there's another that's been open for some time dealing with TS.

**Comment by glebkudr** [comment]
>Would you make a PR 

Never did it previously, I'll try :)
