### ISSUE TITLE
height: auto doesn't work with useSpring hook

### ISSUE THREAD

**Issue by Syynth** [drcmda/react-spring#302]
After doing a little experimenting with Hooks, it seems like the new `useSpring` hook doesn't work with `height: auto` in the same way it does for the `<Spring>` render prop component. 

I've done my best to isolate it [here](https://codesandbox.io/s/811w51o1xj)

**Comment by drcmda** [comment]
It's questionable if it ever will, unless React gives us something to work with. Hooks don't control the render phase, in order to animate auto we would have to render the view for a single frame with end-state values, then measure when it's done, then animate from zero-state to calculated end-state. With hooks we only control values, the view is unknown to us, with a render-child we control everything.

But, and that's the good news, measuring auto yourself with hooks is easier and doesn't create wraps.

**Comment by drcmda** [comment]
Yes, a ref is what <Spring /> uses as well (it clones its function-child and inserts one). But if that were part of useSpring's api i think it would be kind of awkward.

Here's an expander that someone made recently: https://codesandbox.io/s/xlkk6rkx3z

It works like this:

    <Spring to={{ height: open ? contentHeight : 0 }} >
      {props => (
        <animated.div style={{ overflow: 'hidden', ...props }}>
          <div ref={measureRef} style={{ height: 'auto' }}>
            content
          </div>
        <animated.div>
      )}
    </Spring>

This would be quite simple using hooks, just measure out the content, then wrap a container around it and animate its size.

**Comment by Syynth** [comment]
Interesting. I suspected that passing a ref in manually would make for an undesirable API, but I haven't thought of anything better so far. I'll try my hand at writing a useMeasure, but I sort of hope there will be a first party solution to this before long. 

Thanks for the ideas!

**Comment by drcmda** [comment]
Going to close this for now, i've asked Dan Abramov on Twitter the other day and hooks probably won't control the render phase. Let's wait and see if measuring hooks take this off our shoulders.

**Comment by ShanonJackson** [comment]
The problem with useMeasure and Measure is that it works for height but not width?

Seems to be the issue for me.

```
const hello = <div>hello</div>;
export const HeightWidthAuto = () => {
	const [divs, addDivs] = useState([<div>HELLO</div>]);
	const [bind, { width, height }] = useMeasure();
	const props = useSpring({ height, width });
	return (
		<>
			<animated.div
				style={{
					border: "1px solid black",
					overflow: "hidden",
					...props
				}}
			>
				<div {...bind}>
					<div>{divs}</div>
				</div>
			</animated.div>
			<button onClick={() => addDivs((prev) => prev.concat(hello, hello, hello, hello))}>Add Divs</button>
		</>
	);
};
```

**Comment by ShanonJackson** [comment]
Just leaving this here for people whos google search ends them up here looking for a way to animate hooks to height/width auto.

You can have the resize-observer in combination with a inline-block container with spring hook and height/width will animate beautifully.

**Comment by drcmda** [comment]
@ShanonJackson if you have a reduced codesandbox, i could use some for examples

**Comment by ShanonJackson** [comment]
https://codesandbox.io/s/p9vzljv6q

Here is a minimal useSpring height/width auto animation. Two things are critical for both height/width to animate, the first being you can't flow through the changes of the useSpring onto the the same element your observing. Second if you're animating width the thing you're observing must be inline-block as block elements default to 100% width which is 100% of 0px, which means the resize observer will always think the width is 0px and never animate it.

**Comment by DominicTobias** [comment]
@ShanonJackson you're way was inconvenient for me due to the inline thing so I ended up solving it like this. I haven't extensively tested this yet but it works well in Chrome and doesn't have such limitations.

```js
const node = (function heightTestContainer() {
  const node = document.createElement('div');
  node.setAttribute('id', 'heightTestContainer');
  node.setAttribute('style', 'visibility: hidden; position: absolute');
  document.body.appendChild(node);
  return node;
}());

function HeightTransition({ children }) {
  const [height, setHeight] = useState('auto');

  ReactDOM.render(children, node, () => setHeight(node.offsetHeight));

  const props = useSpring({
    native: true,
    to: { height },
  });

  return <animated.div style={props}>{children}</animated.div>;
}
```
