### ISSUE TITLE
Spring component - Chrome 41 encountered error, which leads to removing site from google search

### ISSUE THREAD

**Issue by a7v8x** [drcmda/react-spring#303]
Hi everyone first of all thanks a lot for creating such an awesome and easy to use library.
Recently I have encountered this issue, where my website was completely removed from google SERP results. When I was debuging the issue I found out that the penalizing started to occure after I implemented animation with your Spring component. After removing the animation everything went well again. 

The issue is that Google bot uses Chrome 41 core for rendering crawled websites. If the website cannot be rendered without errors, google will remove it from its SERP results. Unfortunately I needed to remove the animation in order to render the site in Chrome 41 without an error. 

I reproduced everything in this sandbox https://codesandbox.io/s/ko60k3poy3 and I deployed it to now https://csb-ko60k3poy3-qiiyotyjbp.now.sh/. If you would like to test the behaviour in Chrome 41 you can use for example https://www.browserling.com/browse/win/7/chrome/41/https%3A%2F%2Fcsb-ko60k3poy3-qiiyotyjbp.now.sh%2F. 

I would also suggest to improve documentation by adding supported browsers. Please let me know if I can help somehow to fix this issue. It seems to me that if I do not have some bug in the code it is critical error as it can negatively affect number of websites that uses react-spring in production.

Thanks David

**Comment by a7v8x** [comment]
It seems to me that it can be connected with server side rendering in next.js. I will try to force client side rendering tomorrow to be really sure.

**Comment by drcmda** [comment]
SSR indeed seems to have a problem, see: https://github.com/drcmda/react-spring/issues/278

This will be fixed for sure. But other than that, i think supporting browsers really is up to the end-users. With things like babel you could support IE5 if you wanted, but the lib comes pre-transpiled by babel-env nonetheless. If there are features older browsers don't have polyfills will fix that.

**Comment by a7v8x** [comment]
Hi thanks for the comment and sorry for the slow response. I have resolved it by updating the library with the new version of react-spring, where #278 was fixed and by adding polyfills as you proposed. I used directly core-js and imported it into the next pages. Once I will have more time I will find out exactly what polyfills are needed for Chrome 41 support and import them separately for smaller bundle. I believe that it would be useful for easier usage in the future to specify what polyfills are needed for your libary to work in Chrome 41 as its support is must for almost all public websites, so that everyone can keep the bundle size as low as possible without much research what is used in the library. I belive that you can close it now :)

**Comment by rainstormza** [comment]
@a7v8x  Could you show me an example how to add polyfills with core-js in Nextjs page?

**Comment by a7v8x** [comment]
Hi man, yeah sure, actually it works just to imort core js at the top of the each page. Then you should have polyfilled the page. 

```
import React from "react";
import "core-js";
... your page component
```

It is of course better to have some place that you will import it just once and not on every page and also just import polyfills that you need e.g.  import 'core-js/features/array', but this is dependent on the browser that you want to support.
