### ISSUE TITLE
How to mount and cue animation and trigger at specific point in time.

### ISSUE THREAD

**Issue by ddennis** [drcmda/react-spring#305]
How to cue animation and trigger animation at specific point in time.

I am using react-waypoint to detect when element is inside the view-port.
React-waypoint gives helper methods onEnter/onLeave - how do i trigger fadein and fadeout at the right time.

As shown in the example with opacity, i want to mount and render the <div> with the initial opacity value of 0.  

I have made an example here: https://codesandbox.io/s/04xq5wk120 

Kind regards
Dennis

**Comment by drcmda** [comment]
to={{ opacity: this.state.isEntered ? 1 : 0 }}

The `to` prop can be updated any time. You could also create show n hide keyframes: http://react-spring.surge.sh/keyframes

**Comment by ddennis** [comment]
Thanks for replying and for this great library, I am still new to react-spring and i am just trying to understand.

The keyframes solution seems perfect and provides everything i expected from a Spring. Thanks!

What confuses me about the Spring, is that the default usage is to update the **to** prop.
The initial setup, seems so simple and pretty.
```
 from={{ opacity: 0 }}
  to={{ opacity: 1 }}>
```
I was expecting a **start** prop if i wanted to manually start the animation. The same way GSAP/Greensock allows me to pause a tween or timeline. Thanks again.

**Comment by drcmda** [comment]
from gives it the initial values, to animates towards new values. The spring always remembers these. If you want to start a new animation you update `to` again. That way your spring is always reflective of state declaritively.

**Comment by ddennis** [comment]
Thanks again.
