### ISSUE TITLE
Animate parallax children onscroll

### ISSUE THREAD

**Issue by tommy-evolution7** [drcmda/react-spring#309]
I love this library it's awesome. I am blocked currently how to trigger animations on the parallax children on scroll? For example, onscroll to next parallax page, transform scale the children bigger?
I tried using a library called react-on-screen to detect if the component is in the viewport, then animate, but it does not work with parallax.

**Comment by drcmda** [comment]
It would be easy to add something that tracks scroll. I tried, too, but i have a little trouble figuring out the correct math for calculating the offset atm. You want to try? You can simply copy parallax as is (src/addons/Parallax.js) and dump it inside your project.

Starting from line 62 do this:

```jsx
  initialize() {
    const { onFrame, ...props } = this.props
    const parent = this.parent
    const targetScroll = Math.floor(props.offset) * parent.space
    const offset = parent.space * props.offset + targetScroll * props.speed
    const to = parseFloat(-(parent.current * props.speed) + offset)
    this.controller = new Controller({
      space: parent.space * props.factor,
      translate: to,
      onFrame: onFrame && (v => onFrame(v)),
    })
  }
```

Now you can do:

```jsx
<ParallaxLayer onFrame={v => console.log(v)} ... >
```

v is the current translate, you have access to everything else, too in the initialize function (current scroll= parent.current, width/height of a page = parent.space, page factor = props.factor, speed, offset and so on. What you need is that it returns `0` the moment the element appears. 

When you find it, i'd be happy to merge a PR.
