### ISSUE TITLE
IE11 Errors

### ISSUE THREAD

**Issue by vai0** [drcmda/react-spring#310]
IE11 throws a couple JS errors: https://m3727ym26p.codesandbox.io/

![screen shot 2018-11-06 at 11 01 26 pm](https://user-images.githubusercontent.com/1195698/48115492-efcb3f80-e217-11e8-8459-9d374018062f.png)

In our project - with the same Spring implementation - it throws other errors:

![ie11 error 2](https://user-images.githubusercontent.com/1195698/48115458-cc07f980-e217-11e8-86a0-59d4483b000c.png)

**Comment by drcmda** [comment]
Could i see the code where it tries to call .interpolation(...) ? It's probably just a polyfill you need to add.

**Comment by vai0** [comment]
Sorry for getting back so late - fixed after adding `Object.entries` polyfill. Thanks!
