### ISSUE TITLE
Keyframes Not Looping in Async React

### ISSUE THREAD

**Issue by nathanforce** [drcmda/react-spring#313]
When using Keyframes in React's new Async mode, the animation fails to loop.

You can toggle between the two rendering modes here:

https://codesandbox.io/s/5xnoy8lk2x

**Comment by drcmda** [comment]
Damn, this will be tough. It's not Keyframes that seems broken, async messes with springs in general. I've been tracing it for a while and internals look screwed up, things are missing that shouldn't be. I didn't know it had such an impact, i thought strict mode compliancy is good enough. I'll notify you when it's fixed.

**Comment by drcmda** [comment]
Honestly i'm puzzled, async seems to construct the Spring component inside App/Keyframes twice for no apparent reason, calls one didMount, *two* renders on every prop change, two didUpdates. Not sure if it makes sense trying to work against that before detailed info is out on what async means exactly for library authors? 

If you wanna try messing around with it i'd be glad, too.

/cc @gaearon

**Comment by gaearon** [comment]
If something is confusing I'd be happy to look at an isolated case (no react-spring, just the parts that seem surprising) if you file an issue in React repo.

**Comment by nathanforce** [comment]
@drcmda is this fixed or are we deferring until Async is more stable?

**Comment by drcmda** [comment]
I think i'll postpone until react is stable or more informations are out there. I tried to track this down some more and it was so strange, no idea where i would start. I'll re-open when i get further.
