### ISSUE TITLE
Page transition in Next.js, component flash when change route.

### ISSUE THREAD

**Issue by rainstormza** [drcmda/react-spring#325]
I try to implement page transition in Nextjs.

I follow your demo with react-router-dom and it works fine.
https://codesandbox.io/s/1xjj3mqqj

But when I move to nextjs look like animation always flash when I change the route.
http://test-router.surge.sh/
https://github.com/rainstormza/next-route-animation

Not sure what's wrong, but when I use this config animation not flash, but still not as smooth as react-router-dom

```
  from={{
              opacity: 0,
              position: 'absolute',
              width: '100%',
              height: '100%'
  
            }}
```

**Comment by rainstormza** [comment]
@CosmaTrix 
I tried your way but the result still the same.
There are two things that I mention here.
The first thing about a flash component when change page. (https://github.com/drcmda/react-spring/issues/322)
The second thing about when chage page the previous item still remain. (wthout position: 'absolute',),
not sure why I have to use absolute.

Anyway, I look into this repo (https://github.com/xavczen/nextjs-page-transitions/blob/master/pages/_app.js), they use react-spring v5 everything seem ok.

I try to navigate that demo animation won't flash (or remain) (https://page-transitions.now.sh/)

thanks for your help.

**Comment by rainstormza** [comment]
@CosmaTrix It works.
You are correct about `items`, and position relative and width: 100% make page not jumping.
Anyway, about jumping I tried to remove position: relative but everything still ok.
Does it involve about page jumping really?

**Comment by aequasi** [comment]
This doesn't work super well if you use the `useRouter` hook from nextjs. as the props there are all the props for the new page being rendered, so thinks like dynamic pages dont work unless you store the old value with something like react-use's usePrevious
