### ISSUE TITLE
example code for resetting a Spring animation  based on state

### ISSUE THREAD

**Issue by arnoldcamas** [drcmda/react-spring#331]
is there an approach where you can just pass a state and reset the animation  in a spring componenet

**Comment by vai0** [comment]
Something like this would work
```
<Spring 
  from={...} 
  to={...} 
  reset={this.state.isSomething}
>
...
</Spring>
```

**Comment by arnoldcamas** [comment]
@vai0  
can i update the reset property inside at onRest?


let say

```
state = { resetAnimation: false }
<Spring 
onRest={() => {
      this.state.resetAnimation = true;
 }}
reset={this.state.resetAnimation}>
...
</Spring>
```

**Comment by vai0** [comment]
I don't see why not. Remember to use 
```
this.setState({ this.state.resetAnimation: true });
```
instead, and preferably reference that function so it doesn't keep creating a new function on every render.
```
class LoopingAnimation extends React.Component {
  constructor() {
    this.state = {
      resetAnimation: false
    }
  }

  handleOnRest = () => {
    this.setState({
      resetAnimation: true
    });
  }

  render() {
    return (
      <Spring 
        onRest={this.handleOnRest}
        reset={this.state.resetAnimation}
        ...
      >
        ...
      </Spring>
    );
  }
}
```

**Comment by drcmda** [comment]
Yep, like @vai0 said, there's `reset`. Just set it to true/false and it starts from scratch. There's also `reverse`, which switches from/to, which is useful if you want to "animate back".

**Comment by arnoldcamas** [comment]
ok thanks one more question if i do reset the animation , how do i force again the play the animation?

**Comment by drcmda** [comment]
reset={true} will just animate it again. if reset===false, it will only animate fresh/changed props otherwise.

**Comment by arnoldcamas** [comment]
wow thanks for fast feedback, closing this now
