### ISSUE TITLE
Janky animation for Trail with Ant.Design

### ISSUE THREAD

**Issue by mateeyow** [drcmda/react-spring#334]
Good day! I'm not what the issue is but when I try to animate a Button with `Trail` using `native` the animation is very janky and it seems to be lagging. Here's my code: https://codesandbox.io/s/rlrzkk0v8m. Not sure if I'm using the trail right. Your help would be highly appreciated. Thanks

**Comment by drcmda** [comment]
Hi @mateeyow  Wrapping a react element in "animated" isn't going to make it native, at best it allows you to interpolate native styles, but the element will render through react 60fps regardless. Simply wrapping these buttons in <animated.div style={... your props}> ... makes it fast again.

**Comment by mateeyow** [comment]
Hmm, makes sense. It's just very weird since this component is just a normal button and nothing more. Thank you. Closing this issue now.
