### ISSUE TITLE
React Native animated View fails when style is passed as an array instead of an object

### ISSUE THREAD

**Issue by dariocravero** [drcmda/react-spring#337]
Hi,

I'm hitting a bug with how styles are passed into a React Native animated view. If they're passed as a regular object it works fine:
```
style={{
  backgroundColor: '#323232',
  borderWidth: 10,
  borderStyle: 'solid',
  borderColor: 'red',
  opacity: animatedStyles.opacity,
  padding: animatedStyles.padding
}}
```

But if instead the array notation is used, it fails:
```
// the static style would generally be extracted into a StyleSheet object
style={[{
  backgroundColor: '#323232',
    borderWidth: 10,
    borderStyle: 'solid',
    borderColor: 'red',
}, {
  opacity: animatedStyles.opacity,
  padding: animatedStyles.padding
}]}
```

I've made a Snack that shows the problem https://snack.expo.io/@dariocravero/react-spring-rn-array-style-issue. The styles don't show up if the array format is in place.

The logs on the Snack don't show anything but when run on the simulator locally, I get this trace instead:

```
Error: Error: You attempted to set the key `startTime` with the value `1543077307252` on an object that is meant to be immutable and has been frozen.

This error is located at:
    in Spring (at App.js:10)
    in App (at registerRootComponent.js:17)
    in RootErrorBoundary (at registerRootComponent.js:16)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)
    at throwOnImmutableMutation (deepFreezeAndThrowOnMutationInDev.js:70)
    at Controller.start (native.js:936)
    at Spring._this.start (native.js:1158)
    at Spring.componentDidUpdate (native.js:1286)
    at Spring.componentDidMount (native.js:1201)
    at commitLifeCycles (ReactNativeRenderer-dev.js:12144)
    at commitAllLifeCycles (ReactNativeRenderer-dev.js:13495)
    at Object.invokeGuardedCallbackImpl (ReactNativeRenderer-dev.js:92)
    at invokeGuardedCallback (ReactNativeRenderer-dev.js:306)
    at commitRoot (ReactNativeRenderer-dev.js:13701)
```

It only happens when the array format is used.

[This](https://github.com/drcmda/react-spring/blob/0219e9235fd79e79db5aa00baf5141a15b957e99/src/targets/native/index.js#L21) suggests that we're not expecting an array for the style prop.

Might this be a bug or is the style array format not allowed in react-spring for RN?

Thanks!
Darío

**Comment by drcmda** [comment]
I wasn't aware of the array notation even, is there a reason why you'd want to wrap objects into a chain? I only know RN superficially, it surprises me that it can do that, really curious as to the why, though. 

And could i interest you in making a quick PR to fix it?

**Comment by dariocravero** [comment]
As I understand it, the reason for the array notation is [performance for static styles](https://facebook.github.io/react-native/docs/stylesheet) so that objects aren't created twice and in the future it would only send an id instead of the whole object through the RN bridge.

Using StyleSheet, the code I wrote above would actually be:

```
// in the component
<AnimatedView style={[styles.wrapper, animatedStyles]} />

// outside the component
let styles = StyleSheet.create({
  wrapper: {
    backgroundColor: '#323232',
      borderWidth: 10,
      borderStyle: 'solid',
      borderColor: 'red',
  }
})
```

I don't really know what's causing the problem, because even though the [style mapper](https://github.com/drcmda/react-spring/blob/0219e9235fd79e79db5aa00baf5141a15b957e99/src/targets/native/index.js#L21) is expecting an object instead of an array, the issue here seems to be on the `Controller`'s instance instead.

React Native freezes some objects in dev mode in order to catch mutations. For some weird reason, when the style is passed as an array the instance of controller in `Spring` gets frozen. If it is an object instead, the controller isn't frozen, which means that mutating it eg by setting [startTime](https://github.com/drcmda/react-spring/blob/e1342bd46152b348a85148584adbf878eb96e0bd/src/animated/Controller.js#L246) would work.

I'll try to dig a bit deeper and see what I can find. In the meantime, I'm merging the styles inline as a temporary solution be it that they are static or animated :).
