### ISSUE TITLE
Touch multiple stages of interpolation

### ISSUE THREAD

**Issue by yyynnn** [drcmda/react-spring#339]
_Posting here, cuz spectrum is cut off by corp proxy._

So i'm struggling to make a basic drawer menu, touch enabled.
Is there a way to make conditional interpolations in some elegant way (or some way possible), like if some state > x interpolate form current position to highest range value, or if some state < y interpolate to lower range value?
[codesandbox](https://codesandbox.io/s/9yjqo78l5p)
Using react-with-gesture for this to work.

**Comment by drcmda** [comment]
Here's an example that uses useGesture and useSpring together without causing a single render, except the first one of course: https://codesandbox.io/embed/j21ykr7ypw

**Comment by CosmaTrix** [comment]
Hey @yyynnn! Are you looking for something like this [https://codesandbox.io/s/p5nv641x0q](https://codesandbox.io/s/p5nv641x0q)?

I don't know if that's the right way to do so, but I'm using an effect hook to detect if the `down` prop has changed and update the `active` state. I'm then intepolating both `x` and `delta` props (the latter is needed to move the sidebar to the left when inactive) from the `useSpring` hook.

@drcmda What do you think?

**Comment by drcmda** [comment]
Looks good, doing 

```
(v, delta) => `translateX(${Math.min(0, v + delta)}px)`
```

helps as well

**Comment by drcmda** [comment]
tried to remove some code, pretty sure it can be simplified more, but no time right now: https://codesandbox.io/s/kmrk654q0o
