### ISSUE TITLE
Animating transform as a spring, but opacity as ease?

### ISSUE THREAD

**Issue by atomiks** [drcmda/react-spring#340]
This is probably a really basic question, but how do I use the `<Transition />` component to animate a component (a modal) when it mounts, where the `transform` is springy but not `opacity`?

Currently since the opacity is springy, it fades in and out before finally coming to rest which seems weird. Once `opacity` reaches `1`, it should stay there.

```jsx
<Transition
  native
   items={state.isModalVisible}
   from={{ transform: 'translate3d(0,40px,0) scale(0.95)', opacity: 0 }}
   enter={{ transform: 'translate3d(0,0px,0) scale(1.001)', opacity: 1 }}
   leave={{ transform: 'translate3d(0,40px,0) scale(0.95)', opacity: 0 }}
   config={{
     duration: state.isModalVisible ? undefined : 125,
     tension: 150,
     friction: 10
   }}
>
  ...
</Transition>
```

**Comment by drcmda** [comment]
You can give config a function:

```
config={name => name === 'opacity' ? config.default : config.wobbly }
}}
```
