### ISSUE TITLE
TypeScript TransitionProps doesn't extends SpringProps

### ISSUE THREAD

**Issue by SugarDarius** [drcmda/react-spring#341]
Hi ! 

I've made an update to the version 6.1.10 and TS is telling me that TransitionProps does not contain properties such as onStart or onRest. 
After checking the declaration file I've seen that TransitionProps doens't extends SpringProps. 
Can you correct this?

Thanks a lot !
Aurélien

**Comment by drcmda** [comment]
Could you add it via PR? Types are made by contribution, i'll merge as quickly as i can.

**Comment by omung** [comment]
Facing the same issue... please fix it quickly.

**Comment by drcmda** [comment]
Released a patch today, should be fixed.
