### ISSUE TITLE
Animate in order 

### ISSUE THREAD

**Issue by WebDeg-Brian** [drcmda/react-spring#342]
Hello, I just moved to your library from react-motion. Seems very promising. 
I'm currently working on a hero banner that looks like the following:

![](https://user-images.githubusercontent.com/43169879/48971130-b8c59e00-f00d-11e8-959e-a55c3d4d9615.png)

I want first to animate the title, then the subtitle and last the button. I have thought about 2 different solutions:
- Using spring to animate a value from 1 to 3, and get other values based on it.
- Using Trail, but I'm not sure how in this case

So, what can I do to achieve this? Thank you for looking into this

**Comment by drcmda** [comment]
Trail is good for this kind of stuff. I would recommend using this one.
