### ISSUE TITLE
SVG Morphing not working, Same paths morph properly with GSAP

### ISSUE THREAD

**Issue by Shub1427** [drcmda/react-spring#343]
Problem having login in to https://spectrum.chat, thus posting here.

Having trouble animating a simple path to morph into a different path.
Codesandbox demo can be found [here](https://codesandbox.io/s/42pqojyn37).
The Problem is, Paths do change to the `from` to `to`, but there is not animation happening inbetween these two states.

Thought, it would be related to some wrong exported paths, so created a working GSAP example as well [here](https://codepen.io/shub1427/pen/vQbzeW)

I tried to find react-spring examples for SVG morphs, but cudn't find much, except [React Spring Morphing Example](https://github.com/drcmda/react-spring/blob/master/examples/demos/morph/index.js)

**Comment by drcmda** [comment]
Wait, your paths have the same structure, so it's even easier, you don't need any interpolator for this: https://codesandbox.io/embed/z6r70qzrm

**Comment by drcmda** [comment]
I think that's flubber now. I wasted a day on figuring out maxSegments in the demo i posted, it has some specifics. d3's can be quite complex as well. generally morphing is not trivial so some paths or shapes need special consideration. if you use a dedicated svg interpolator, react-springs job is just moving between 0 and 1, though.
