### ISSUE TITLE
@types/react/index has no exported member 'ForwardRefExoticComponent'

### ISSUE THREAD

**Issue by omung** [drcmda/react-spring#344]
so I upgraded react-sprint to react-spring@6.1.10 and then I got this error.... Can't say for sure but seems like this PR broke it https://github.com/drcmda/react-spring/commit/281993dca369c678903117b9fcc31eb790ccc800

Please let me if require more information

**Comment by drcmda** [comment]
never heard of "ForwardRefExoticComponent" before, is that a new react primitive? Maybe updating react will fix it. all TS types are contributed, if this one is maybe targeting a brand new react version maybe it should be rolled back?

**Comment by faltysad** [comment]
Same problem occured for me. Downgrading to `react-spring@6.1.0` fixed it for me.

**Comment by drcmda** [comment]
merged a pr today & released a patch, should be fine now.

**Comment by rzkhosroshahi** [comment]
I have still this issue in the latest version.

**Comment by jj-12** [comment]
I'm also seeing this issue with the latest version of react-spring.  Was previously on v.7.

**Comment by jacobrask** [comment]
What version is your `@types/react`?

**Comment by jj-12** [comment]
Thanks for the quick response!  I'm on `16.4.14`

**Comment by woosie10** [comment]
Same issue with `@types/react 16.4.11` and `react-spring 8.0.7`. It seems like the issue was introduced in `react-spring 7.2.1`, as `react-spring 7.2.0` works for me, but after that version it does not.

**Comment by jacobrask** [comment]
You should try upgrading `@types/react` to >`16.8`, hooks are also missing from 16.4 as far as I know.

**Comment by wss534857356** [comment]
Any update about this?

**Comment by aleclarson** [comment]
@wss534857356 This shouldn't be an issue with v9 (`react-spring@next`). Please open a new issue if there is.
