### ISSUE TITLE
Bug: Trail throws ref error in HMR environment

### ISSUE THREAD

**Issue by ooloth** [drcmda/react-spring#349]
I'm seeing the same error mentioned at the end of [this comment about Transition](https://github.com/drcmda/react-spring/issues/26#issuecomment-441046437) when using `Trail` in the latest version of Gatsby, which [adds](https://github.com/gatsbyjs/gatsby/pull/10259) the following setting to help `react-hot-loader` [work properly](https://github.com/gaearon/react-hot-loader/issues/1088#issuecomment-441191107) with React hooks:

```js
import { setConfig } from "react-hot-loader"

setConfig({
   ignoreSFC: true,
   pureRender: true,
 })
```

Here is the error:

```sh
Warning: Function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `AnimatedComponent`.
```

This error only appears [after modifying](https://github.com/gatsbyjs/gatsby/issues/9489#issuecomment-440068532) the `react-hot-loader` config, so it seems tied to the RHL settings.

`Trail` still seems to work fine in spite of this error, so I just wanted to check whether the error is important or can be ignored.

**Comment by drcmda** [comment]
Hard to say as i don't know RHL's innards. They probably switch something that previously carries a ref into something that now cannot. I think RHL will only become truly stable once hooks are more prevalent. I'm using the same forwardRef pattern that is on the React page in AnimatedComponent otherwise.

**Comment by ooloth** [comment]
Thanks! Good to know this isn't a react-spring issue. 

I know the RHL maintainers are working hard to prepare for hooks, so I let them know about this error and I'm sure they'll get everything worked out soon.
