### ISSUE TITLE
How to turn off animation in ParallaxLayer?

### ISSUE THREAD

**Issue by janoist1** [drcmda/react-spring#350]
Hi! I'd like to turn off the animation of some `ParallayLayer`. How to achieve this? If you gave me some instructions I'd be happy to create a PR too. Lots of thanks.
Update:
What I have tried is to add an extra prop to the `ParallayLayer` called `config` and passed something like: `{ tension: 0, friction: 0, precision: 0, delay: 0, duration: 0 }`.
This has made the layer fixed but is a bit glitchy...

**Comment by drcmda** [comment]
could you try duration: 0.000001 ? i believe that if duration is falsy it will take spring friction/tension instead. I probably have to check against it being undefined though to support duration: 0
