### ISSUE TITLE
Unmount after transition.

### ISSUE THREAD

**Issue by Godsenal** [drcmda/react-spring#43]
Hi. First of all Thank you for the awesome library!
I'm trying to make notification list with `<Transition>`. 
https://codesandbox.io/s/6v4xqkmlmk
This is my sample code. What i'm tying to do is,

1. Push notification component to the `this.state.notifications`, when button is clicked.
2. Remove notification after timeout or has been clicked.

So, `enter` and `leave` props working correctly. Opacity is set 0 to 1 when Enter, 1 to 0 when Leave. 
But my problem is, when component has removed by click or timeout, it still exist in Dom.
I must update state( change value on input, remove other component ...) to actually remove this component.

Did i miss something..?

**Comment by drcmda** [comment]
@Godsenal this is something that sneaked into the last update i believe. I am aware of it, will be fixed soon.

**Comment by Godsenal** [comment]
Thanks a lot!!

**Comment by drcmda** [comment]
@Godsenal it should be fine now, @4.1.4
