### ISSUE TITLE
v4.1.3 route transitioning does not remove previous DOM nodes

### ISSUE THREAD

**Issue by nickmcmillan** [drcmda/react-spring#44]
Hi there, thanks so much for your work on this library.

In your React Router example after a transition is complete the old DOM node is removed (which is correct behavior); https://codesandbox.io/embed/xo0lrqw2nz

In this example if I upgrade the library version to v4.1.3 (which is the latest version at time of writing) I notice the previous DOM nodes no longer get removed as they should. Here's my fork with the only difference being the version number: https://codesandbox.io/s/yv2458ljxv

**Comment by drcmda** [comment]
Yep, sorry for that, it's the same issue as https://github.com/drcmda/react-spring/issues/43

The Transition component has a bug in the latest that prevents it from removing stale components. Fix will come up.

**Comment by drcmda** [comment]
@nickmcmillan it should be fine now, @4.1.4
