### ISSUE TITLE
Update readme on how to use react-spring with react-router

### ISSUE THREAD

**Issue by mvasin** [drcmda/react-spring#51]
There is a section in readme called "Parallax and page transitions", that contains some guidance on parallax, but not about page transitions, at least not in `react-router` terms.

I'd love to find out out how to use `react-spring` and `react-router` together, and have readme updated on that.

**Comment by drcmda** [comment]
There's an example: https://codesandbox.io/embed/mjnwrk1o3p

**Comment by mvasin** [comment]
OK, I missed the link in the readme, now I see it. Thanks!
