### ISSUE TITLE
"auto" value does not work with react-router (or any other context-based APIs)

### ISSUE THREAD

**Issue by taylorlapeyre** [drcmda/react-spring#52]
Since the addition of `"auto"`, any components rendered inside of a Spring that uses `'auto'` as a value do not receive the "router" context, resulting in bugs:

![screen shot 2018-04-17 at 4 38 23 pm](https://user-images.githubusercontent.com/1610503/38904178-cb07f9a4-425d-11e8-9445-f5b77af7b1ca.png)

![screen shot 2018-04-17 at 4 39 21 pm](https://user-images.githubusercontent.com/1610503/38904207-effc9e04-425d-11e8-958f-f58ad197161e.png)

This is likely due to the [psuedo-portal approach](https://github.com/drcmda/react-spring/blob/master/src/animated/targets/react-dom/fix-auto.js) of the `fixAuto` file. 

I have a suspicion that this is due to not using `ReactDOM.render` instead of `ReactDOM.createPortal` (the latter preserves context). Any other ideas? Happy to help with a fix, just need to figure out what direction we'd want to go in.

**Comment by drcmda** [comment]
@taylorlapeyre could you try with @4.2.1-beta.0 ? It *should* be fixed now. It attempts to render out the middlewares result instead of relying on a promise, thereby the fragment ends up in the same render-tree, which hopefully doesn't break context.

**Comment by taylorlapeyre** [comment]
@drcmda Yes, I'll give it a shot!

**Comment by taylorlapeyre** [comment]
@drcmda it's working beautifully now!

**Comment by jeroenvisser101** [comment]
@drcmda Will test with router and styled-components w/ ThemeProvider, will update

**Comment by jeroenvisser101** [comment]
Totally works now!

**Comment by jeroenvisser101** [comment]
Update: tried this a little more and it seems that when the portal is created, the style of the page is (very briefly) removed. When you have custom fonts you can observe fonts changing back to serif font.

**Comment by jeroenvisser101** [comment]
font-family is set on `:root`. Also, the Spring and `animated.div` should not (?) affect the rest of the page, right? There's 2 frames in that video where the whole page's font-family resets for some reason.

**Comment by drcmda** [comment]
Spring and animated.div are just regular components, must be something else. The portal renders off-screen in a div set to `position:static;visibility:hidden;`, but it isn't shown, we pick bounds and then the element renders like always, with `auto` being overwritten by the new bounds. I couldn't imagine any of it would have an impact on the font-family. Here's some info on how fout can come about: https://www.paulirish.com/2009/fighting-the-font-face-fout/

**Comment by drcmda** [comment]
closing this for now, should something else come up i can reopen

**Comment by jeroenvisser101** [comment]
@drcmda yep, issue was unrelated after all, spring works great now after ditching styled-components' `injectGlobal` for font injection
