### ISSUE TITLE
Generate Keyframes from Adobe After Effects

### ISSUE THREAD

**Issue by subtleGradient** [drcmda/react-spring#54]
Maybe reuse some of the code from Facebook Keyframes After Effects exporter:
https://github.com/facebookincubator/Keyframes/tree/master/scripts
https://github.com/facebookincubator/Keyframes/blob/master/js/src/AECompToKeyframesAnimation.js

Or maybe use the Lottie stuff instead.
http://airbnb.io/lottie/
https://aescripts.com/bodymovin/

(I'm not as familiar with how Bodymovin works)

**Comment by subtleGradient** [comment]
react-spring is crazy awesome! I'm excited to start playing around with it

**Comment by drcmda** [comment]
Thanks! I'm not so familiar with these AAE, Bodymoving and Lottie, but if you are familiar with any of it, you could try setting up a primitive. The lib exposes animateds low level stuff, like AnimatedValue and so on. For instance from what i've seen in lottie-react-native, the API could be mapped like that if you wanted. PR's for new primitives are definitively welcome!
