### ISSUE TITLE
onRest not called when using Transition

### ISSUE THREAD

**Issue by jeef3** [drcmda/react-spring#55]
`onFrame` works, but `onRest` is never called when using `<Transition />`.

**Comment by drcmda** [comment]
Transition doesn't technically have a beginning and an end, it just reacts to random child-component lifecycles. Could you describe what you're trying to do?

**Comment by jeef3** [comment]
Yeah, it's a little bit of a weird case, especially when it looks like `Transition` is designed for use with lists. I'm using `Transition` for its enter/leave capabilities on a _single_ component. So I effectively want to know when that component has finished being shown or hidden.

_I looked in the src and `onRest` is right there, just not passed through to `Spring`. So I created #56. Not sure now if you'll want that merged though._

**Comment by drcmda** [comment]
Ah, so it's that, it's fine - it takes a list or a single component. Transition is kind of tricky.

**Comment by jeef3** [comment]
> Transition is kind of tricky.

Yup! :smile:

The longer version: 

I don't like `ReactTransitionGroup`'s API. It is geared towards adding/removing classes. I prefer working with `Animated` for its interpolation (given a 0–1 progress value, interpolate for me from `15px`–`213px`) so I can write up a custom `translate3d(x, y, z)` style.

I also want the enter/leave states handled for me. Leave is the most important as I don't want to have to worry about removing the element myself _after_ the transition has finished.

`Transition` currently does everything I need — I love that I can opt to provide an easing instead, because sometimes I want spring, sometimes I want easing.

In my particular case, I'm doing a FLIP animation on a single component. So I want to know when the animation has ended so I can hide the animated component, and show the real one.

**Comment by drcmda** [comment]
@jeef3 When you feel like you have something that resembles a general usecase and it warrants a Flip primitive, would love to get something like this as a pr. As you've seen, the primitives are more-or-less simple classes that wrap around animated, like so: https://github.com/drcmda/react-spring/blob/master/src/Trail.js

There's been a request for it already: https://github.com/drcmda/react-spring/issues/9 but i just haven't done it myself yet, i learned about flip here, in this tracker. Silly i know...

**Comment by jeef3** [comment]
Will see what I can do! The use case in #9 is a little different to mine, but yes, I'll see if I can pull together a better use case.
