### ISSUE TITLE
Transition animation issue

### ISSUE THREAD

**Issue by ugin** [drcmda/react-spring#67]
Hey, I found an issue that was introduced in v4.0.2 in [Transition.js](https://github.com/drcmda/react-spring/blob/master/src/Transition.js#L173)

Working example: https://codesandbox.io/s/2jo121296p (v4.0.1)
Example with issue: https://codesandbox.io/s/1rv0w62rkj (v4.0.2+)

On both examples click fast on the green body. In the working example the animation goes in one direction, in the one with the issue, the animation goes in both directions.

**Comment by drcmda** [comment]
@ugin  My fault for not spending time on the docs early on - here's the explanation: https://github.com/drcmda/react-spring/issues/66

**Comment by drcmda** [comment]
Found the issue. Need to figure out a minor detail and i'll update.

**Comment by drcmda** [comment]
@ugin  Should be fine in @5.0.0

Just watch out for a little inconsistency in your sandbox:

```jsx
       <Transition
          native
          keys={selected}
          from={{ opacity: 0, transform: 'translateY(3rem)' }}
          enter={{ opacity: 1, transform: 'translateY(0rem)' }}
          leave={{ opacity: 0, transform: 'translateY(-4rem)' }}>
          {style => <a.div style={{ ...textStyle, ...style }}>{selected}</a.div>}
        </Transition>
```

You forgot to set Transition to `native` (although you use animated.div in the render fn), and translateY(0) -> translateY(4rem) doesn't interpolate well because the unit it missing on the first. use `0rem` and it should be fine.

**Comment by ugin** [comment]
Awesome work sir! Started reading the source yesterday, I'm new to animations in React, really useful, thank you!
