### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by ZakKa89** [drcmda/react-spring#70]
I can't find anything in the documentation about browser support. 
I tested a trail animation in crossbrowsertesting and got the following error on iphone ios, but also on older chrome versions on android:

![image](https://user-images.githubusercontent.com/24491661/39308497-e34b601e-4965-11e8-91ec-b080e1d8ebd8.png)

Could I get a little bit more insight on browser support, or any advice to fix this?

**Comment by drcmda** [comment]
@ZakKa89 is it just Object.values or did you see something else? I could use Object.keys instead. Though i think the lower you go with support there'll be something eventually that isn't understood (for instance, Promises). Babel with node_modules included would polyfill these things away. Is that an option? Do you know if you have at least promise support?

**Comment by ZakKa89** [comment]
We do use babel to transpile, but we might have to check our babel settings. We're going to check it out, at least I know where to look.

**Comment by ZakKa89** [comment]
Yes  I will try that as well

**Comment by drcmda** [comment]
I have published 5.1.0, which uses Object.values.
