### ISSUE TITLE
react-spring.es.js?1586:2126 Uncaught (in promise) TypeError: __WEBPACK_IMPORTED_MODULE_4_react___default.a.createContext is not a function

### ISSUE THREAD

**Issue by anilljoshi** [drcmda/react-spring#71]
it showing me following error: react-spring.es.js?1586:2126 Uncaught (in promise) TypeError: __WEBPACK_IMPORTED_MODULE_4_react___default.a.createContext is not a function.

Here is my code:
<Router>
        <ErrorBoundary fallbackComponent={AppError}>
           <Transition
                native
                config={{ tension: 1, friction: 10 }}
                keys={location.pathname.split('/').filter(a => a)[0]}
                from={{ transform: 'translateY(500px)', opacity: 0 }}
                enter={{ transform: 'translateY(0px)', opacity: 1 }}
                leave={{ transform: 'translateY(500px)', opacity: 0 }}>
                {style => (
                  <Switch>
                    <Route exact path="/" component={Homepage} />
                    <Route path="/login" component={Login} />
                  </Switch>
                )}
          </Transition>
          <AppInfo />

        </ErrorBoundary>
      </Router>

**Comment by TrySound** [comment]
@anilljoshi Do you have any errors in terminal where you run webpack?

**Comment by TrySound** [comment]
@anilljoshi You probably need to update react. spring requires react 16.3

**Comment by TrySound** [comment]
Take a look at npm/yarn warnings please
https://github.com/drcmda/react-spring/blob/master/package.json#L75-L76
