### ISSUE TITLE
import { Spring } from 'react-spring' collapses my react application

### ISSUE THREAD

**Issue by orarr** [drcmda/react-spring#73]
Dependencies 
"react": "^15.6.0",
"react-spring": "^5.0.1",

Just the import of 'react-spring'
`import { Spring } from 'react-spring'` 
and react renders nothing with the 
 `<div id='root' ></div>` empty.
If i comment the import line, everything becomes Ok.
I find it strange. And no error is reported.

**Comment by orarr** [comment]
So i just degraded to v4.2.1 and it works perfect.

**Comment by TrySound** [comment]
@orarr react-spring 5.*.* requires react 16.3.*.

**Comment by TrySound** [comment]
Take a look at npm/yarn warnings please
https://github.com/drcmda/react-spring/blob/master/package.json#L75-L76
