### ISSUE TITLE
Mouseover Parallax

### ISSUE THREAD

**Issue by tim-soft** [drcmda/react-spring#8]
Is it possible with this library to make a hover/mouseover based parallax effect similar to this example http://matthew.wagerfield.com/parallax/

**Comment by drcmda** [comment]
@tim-soft certainly, though atm there's no defined primitive for it. Doing it yourself would probably involve watching the mouse and a couple of springs. But if you do have an idea how to pull this off declaratively, i'd be interested in following this through.

Would you take a look at the two parallax demos on the front page, look at the primitives there and maybe reflect on how you'd do something like that just with an input device.

**Comment by tim-soft** [comment]
In the example I provided, the mouse's (x, y) position controls the parallax, although I've seen other fixed-viewport implementations controlled by the mouse scroll wheel.

There wouldn't be a need for pages per se, but a z-index hierarchy, probably in order of smallest to highest child layers(?). Each layer would have a `stiffness` and `damping` prop and a style prop to help with positioning/size.

**Comment by drcmda** [comment]
When i find time i will look into this and try to add a primitive.

**Comment by leonascimento** [comment]
Hey guys, this is a great enhancement, @drcmda can I do it?

**Comment by drcmda** [comment]
@leonascimento For sure! 😃

**Comment by drcmda** [comment]
Ran into this today, turns out, it's super, super easy to do: https://twitter.com/0xca0a/status/1063023461881266176

**Comment by DaniAcu** [comment]
> @tim-soft @leonascimento Ran into this today, turns out, it's super, super easy to do: https://twitter.com/0xca0a/status/1063023461881266176

The codesanbox referenced in that twitter is not working because the url images are broken, I updated and create a forked sandbox, let me sharing it here to any other that want to see a functional example. 

Maybe could be nice have a reference in the documentation? @drcmda What do you think?

Codesanbox: https://codesandbox.io/s/mouse-parallax-with-react-spring-9j9t3l
