### ISSUE TITLE
Keyframe doesn't animate background prop

### ISSUE THREAD

**Issue by dannymy** [drcmda/react-spring#80]
The [Keyframes/single script demo](https://codesandbox.io/embed/j1w4355593) from the examples section does not animate background property, when `React` and `react-spring` are updated to `^16.3.1` and `5.1.1` versions respectively. Can be reproduced [here](https://codesandbox.io/s/9y3o1y9824), on a forked sandbox.

**Comment by drcmda** [comment]
@dannymy should be fixed in 5.1.2
