### ISSUE TITLE
template object for native springs

### ISSUE THREAD

**Issue by thebuilder** [drcmda/react-spring#81]
Trying to get a native Spring to work, and came across `import {template} from 'react-spring` in some of the examples. But there is nothing called `template` inside the project, and trying to import it just returns undefined. Is it an old outdated value? If so what should you do instead?

**Example:** https://codesandbox.io/embed/vvmv6x01l5

**Comment by drcmda** [comment]
Template was removed a while ago, see: https://github.com/drcmda/react-spring/blob/master/API-OVERVIEW.md#native-rendering-and-interpolation-demo

I fixed the demo, too

**Comment by drcmda** [comment]
I’ll make a new demo/examples page soon. template was an animated concept, animated the library. But we don’t need it.
