### ISSUE TITLE
Best way to implement an infinite fade-in fade-out?

### ISSUE THREAD

**Issue by Tsury** [drcmda/react-spring#85]
I want an image to fade-in and then fade-out in intervals of 1s with some easing. I'm not sure I understand what's the simplest way to achieve this using react-spring.

**Comment by drcmda** [comment]
There are several ways to do it,

for instance i have an app that displays some kind of heartbeat:

![heartbeat](https://user-images.githubusercontent.com/2223602/39957159-6a881f56-55ee-11e8-8a42-6b9a227defcd.gif)

I do it this way:

```jsx
state = { pulse: true }

componentDidMount() {
    this.togglePulse()
}

componentWillUnmount() {
    clearInterval(this.pulseIntervall)
}

togglePulse = () => {
    clearInterval(this.pulseIntervall)
    this.pulseIntervall = setInterval(() => this.setState(state => ({ pulse: !state.pulse })), 1000)
}

    ...
<Spring native from={{ scale: 0 }} to={{ scale: pulse ? MAX : MIN }} ...>
```

You could also wait for animations to stop via onRest={() => this.setState(state => ({ fade: !state.fade })}

Or time-based animations with keyframes: https://github.com/drcmda/react-spring#timeduration-based-implementations-and-addons-demo

**Comment by strobox** [comment]
`
const Content = (props) => {

  const [running,setReset] = useState(1); // 1 anim running, 0 resetting, -1 restarting
  useEffect(() => {
    if(running <= 0) { setReset(running == 0 ? -1 : 1)}
  }, [running==0 || running])

  return (
    <div>
        <Spring
            reset={running===0}
            onRest={() => running > 0 && setReset(0) }
            from={{ opacity: 0 }} to={{ opacity: 1 }}>
          {props => <div style={props}>hello</div>}
        </Spring>
    </div>
  )
}
`
