### ISSUE TITLE
Animating many paths with Spring flips coordinate sign

### ISSUE THREAD

**Issue by LaxisB** [drcmda/react-spring#87]
I'm doing an experiment with animating poly-based images into each other.  
Basically i have two images each containing 200 triangles of differing path, fill and opacity.

When i switch in-between them using a Spring with the native attribute, it sometimes causes certain coordinates in the path to have a flipped sign, i.e `d="M158,-130 L 66,24 L 129,2Z"` is instead rendered as `d="M158,130 L 66,24 L 129,2Z`

a reproduction can be found here: https://github.com/LaxisB/react-spring-path-issue

video: https://youtu.be/lKXW0CpNwC0
0:00-0:05 works fine if i use the 'reset' image with `d="M0,0 L 0,0 L 0,0 Z" and white fill`
0:06-end switching from one image to another without using the reset, causes some paths to be flipped: appearing as 'holes' in the image

**Comment by drcmda** [comment]
@LaxisB could you try with 5.1.10? There's some regexp in interpolate that probably wasn't tight enough: https://github.com/drcmda/react-spring/commit/b673ab7a42a5a5e24bb9fa6e4668ca72df5c3319#diff-90da51f1f7c22bcbcd56dd284e2a08faL122

Does this fix it? Tried your demo and it looked better to me.

**Comment by drcmda** [comment]
Btw, the key prop should be on the path:

    <animated.path key={p.id} ... />

Spring is just a hoc

**Comment by LaxisB** [comment]
i can confirm this is fixed.
thanks for the fast update

**Comment by drcmda** [comment]
@LaxisB it looks awesome btw, could i use that as an example, basically just dump it into a codesandbox?

**Comment by drcmda** [comment]
Like so: https://codesandbox.io/embed/9jj8py13l4

**Comment by LaxisB** [comment]
sure. the images belong to ubisoft though.
i can make you one with free stock photos (i guess mountains are a nice motive) .

the process is basicaly running an image through [primitive.js](https://ondras.github.io/primitive.js/), converting the svg to code and then animating it.

**Comment by LaxisB** [comment]
here's a demo with free images:
https://codesandbox.io/s/y21r23o079
https://codesandbox.io/embed/y21r23o079  
  
i added a comment explaining the concept.
if that's too much for the demo, feel free to fork/edit

**Comment by drcmda** [comment]
@LaxisB Awesome, i'll add this so others can learn. Btw, how do you create these images, with the same amount of polygons? I love the effect of it!
