### ISSUE TITLE
 entry.interpolation._interpolation is not a function

### ISSUE THREAD

**Issue by rubenspgcavalcante** [drcmda/react-spring#91]
First of all thanks for this awesome library!
So, I've tried the example based on [this one](https://codesandbox.io/embed/9jj8py13l4) using the `primitive` go lib to generate the SVGs.
Then I fetch these SVGs and convert them using the DOMParser API, just to get the attributes of each path node and apply on the `<animated.path />`.
But when Spring tries to animate from one SVG to another, it throws an exception:
` entry.interpolation._interpolation is undefined`
Checking the code, it does verify if `entry.interpolation` exists, but don't check the inner `_interpolation`:
```js
 // Deal with interpolations
 var previous = entry.interpolation && entry.interpolation._interpolation(entry.animation._value);
```
You can check it directly here https://react-spring-sample.surge.sh/ (just click on the image)
And the source here: https://github.com/rubenspgcavalcante/react-spring-sample

**Comment by drcmda** [comment]
@rubenspgcavalcante looks like the example is incomplete, it's missing the svg's.

**Comment by rubenspgcavalcante** [comment]
Hello @drcmda!
Both images are requested on the app start (you can see on the network tab, both in base64 format, because of the webpack url loader). I forgot to add to the repo (I'll do it right now and post here).

So, both have exactly the same number of paths (50). So basically I map each one to other to try to make the animation.

**Comment by rubenspgcavalcante** [comment]
Hello @drcmda ,
So, I've updated the example to use the file-loader to load the svg (the url loader change polygons to paths to make it smaller). Also put a `console.log` on the number of polygons I'm using (**50 in each one**). You can see it [here](https://github.com/rubenspgcavalcante/react-spring-sample/blob/master/src/assets/arara.primitive.svg?short_path=c0b62af) and [here](https://github.com/rubenspgcavalcante/react-spring-sample/blob/master/src/assets/tucano.primitive.svg?short_path=49cf65a).

So, I just map each polygon of both images to try to make them animate.

**Comment by rubenspgcavalcante** [comment]
I'm getting another error message now (instead of undefined, it's says `_interpolation` isn't a function) 🤔

**Comment by drcmda** [comment]
@rubenspgcavalcante sorry i was(/still am) a little busy due to work and the react-native stuff. It would be such a help if you could debug deeper. You can actually import from src directly "react-spring/src/targets/web/index" (in the latest version) and get to debug sources that way. Would be interesting why _interpolation is either undefined or not a function (what would it be if it isn't one ... ?).

**Comment by drcmda** [comment]
@rubenspgcavalcante finally had time - it was something completely unrelated, it didn't recognize your fill color, it's working now as expected in the latest version.

**Comment by rubenspgcavalcante** [comment]
Awesome! Thanks @drcmda :)
