### ISSUE TITLE
Parallax effects with custom Layer heights and not using top-level Parallax for scrolling

### ISSUE THREAD

**Issue by natew** [drcmda/react-spring#92]
We have a site that has some specific needs for it's sizing of sections. A few aren't compatible with Parallax. Namely we have both min-height and max-height requirements.

How hard would it be to have Parallax let you do the following:

1. Pass in a Layer height
2. Allow it hooking into your own custom scroll layer

Number two is important because we want to also keep scroll bounce / have the body scroll.

**Comment by drcmda** [comment]
@natew From what i remember it simply goes 100% of the parent container, so it should respect the height if its either relative or absolute. The parallax in the main page demo for instance sits in a little grid-box. 

If you mean changing the height of a layer in general, then you can do this with the factor prop, it defaults to 1 (100%), 2 would be 200%, 1.5 150%, etc.

**Comment by drcmda** [comment]
You can also copy this file: https://github.com/drcmda/react-spring/blob/master/src/Parallax.js and change styles - or perhaps make a PR to make it more flexible. If you're going for a local fork, all the imports there you can get directly from react-spring.

**Comment by natew** [comment]
@drcmda I should have specified better my specific use case. I'll investigate and comment back if this already works but I thought it didn't.

Basically: I have sections that are:

```
height: window.innerHeight;
max-height: 1200px;
min-height: 600px;
```

The max and min to me looked impossible as Parallax was assuming effects based on window.innerHeight. So I think the real thing would be to be able to define a "viewport height" of your own and have parallax use that. But of course I can fork and implement.

**Comment by drcmda** [comment]
It shouldn't have anything to do with innerHeight/Width - it takes the height of the parent container - if its either relative or absolute. Like this: http://react-spring.surge.sh/ (upper left, upper middle). Wouldn't this fulfill it?

**Comment by drcmda** [comment]
for clarity of the ongoing issues i'll close and re-open again when new info comes up

**Comment by 0m15** [comment]
Hi, I've played a bit with the code and made a version that works with "dynamic" heights. 
It also plays well with responsiveness. Though, it's still not tested properly (I just tweaked it for my needs, I cannot guarantee it works properly for others) and some props are not being used anymore (like the `factor` prop).

However, here you go: https://github.com/0m15/react-spring
