### ISSUE TITLE
How to toggle Transition animation with state in keyframes demo?

### ISSUE THREAD

**Issue by bringmethecode** [drcmda/react-spring#93]
Hello, I'm trying to create an animation like the one from the keyframes demo, but instead of automatically trigger it, I want to enable the animations when state changes (when users clicks a button), so I am using Transition on this.content so I can have control of the leave animation.

But I don't know whats left to achieve that... this is what I have so far, a fork from the demo: https://codesandbox.io/s/z2xozxmwjx

I appreciate any help.

**Comment by drcmda** [comment]
@bringmethecode 

remove componentDidMount and try this:

```jsx
  open = false
  toggleAnimation = async () => {
    this.open = !this.open
    if (this.open) {
      this.container(Spring, { from: { x: -100 }, to: { x: 0 } })
      await delay(100)
      await this.content(Trail, { from: { x: -120, opacity: 0 }, to: { x: 0, opacity: 1 } })
    } else {
      this.content(Trail, { to: { x: -100, opacity: 0 } })
      await delay(100)
      await this.container(Spring, { to: { x: -100 } })
    }
 }
```

The idea behind keyframes is that you can use it to control your animation-content.

**Comment by drcmda** [comment]
@bringmethecode I've checked in some new stuff today that'll make things like the above easier: https://twitter.com/0xca0a/status/999390220666703872

The old api (like in the snippet i copied) will still work, but using these slots it's going to take care of async stuff and race conditions.

**Comment by bringmethecode** [comment]
Hey, sorry for the late reply, thanks for the insight @drcmda, going to check that sandbox right now.

Off-topic, but you are the founder of Paranoid Android right? what a legend! thanks for this great library.

**Comment by drcmda** [comment]
@bringmethecode oh, you used PA? Yep, i am. :-)
