### ISSUE TITLE
[Performance] Can't animate larger amounts of children in Trail animation

### ISSUE THREAD

**Issue by ZakKa89** [drcmda/react-spring#97]
I found out I can't animate more than a certain amount of items using Trail before my browser just straight up freezes. I think the limit is around 15, but it might also have to do with the type of transition. The target in my use case is quite high, around 25. 

This can be reproduced using your codepen sandbox by adding more items to the state:
 https://codesandbox.io/embed/vvmv6x01l5

note: I used native rendering, but could reproduce with and without native rendering.

**Comment by sbrichardson** [comment]
I noticed the same, hadn’t looked into it yet, thought possibly I was doing something wrong. Can you provide any recommendations on the preferred way to handle, or comfortable max?

**Comment by natew** [comment]
Also noticed, and thought it was my fault!

**Comment by drcmda** [comment]
Strange, there seems to be something that's blocking it, then after a while it starts animating.

**Comment by drcmda** [comment]
It's something in animated, the flush function is called thousands of times. It should only be called once. Something's clearing the cached animation-tree while it's animating.

**Comment by drcmda** [comment]
Should be fixed. Then again, physics-based trails in general seem to be super expensive, i had no idea. To make a duration based trail would be simple, if you still face issues i'd suggest doing something like this:

```jsx
class DurationTrail extends Component {
  render() {
    const { children, delay, keys, ...props } = this.props
    return children.map((child, i) => {
      const firstDelay = i === 0 && delay
      return (
        <Spring
          key={keys[i]}
          {...props}
          delay={firstDelay + (i * 50)}
        />
      )
    })
  }
```
